### ISSUE TITLE
Field types are unable to be changed

### ISSUE THREAD

**Issue by wrrnlim** [buttercup/buttercup-desktop#1166] opened 2022-09-07 04:25 UTC
```
Desktop @ v2.17.0
Core @ v6.16.2

Flags: installed
```

When creating a new entry, the custom fields types are unable to be changed.

Steps to reproduce:

1. Create an entry with a custom field. Set the field type to `Text (default)`
2. Save the entry
3. Edit the entry and change the field from type `Text` to type `Password`
4. Save the entry again

The field will still remain as a `Text` type, without hiding the string as the `Password` type does.

**Comment by perry-mitchell** [comment] 2023-05-12 07:00
I'm unable to reproduce this on the latest build (2.20.1). I believe this was most likely fixed by another save bugfix.

**Closed by perry-mitchell** 2023-05-12 07:00 UTC

**Comment by ldexterldesign** [comment] 2024-04-14 22:44
👋

I suggest following up / subscribing [here] - if y'all agree then please close this issue to help the repo' maintainer

Hope this helps!

Regards

[here]: https://github.com/buttercup/buttercup-desktop/issues/1219
