### ISSUE TITLE
Unhandled error when updating (windows)

### ISSUE THREAD

**Issue by diguifi** [buttercup/buttercup-desktop#746] opened 2019-02-02 01:34 UTC
If I open the app without admin rights and get prompted to update, an unhandled error is thrown.
If I execute as admin and do the same, the app updates normally.

I see two approaches to this:
- Handling the exception and prompting something about it
- Automatically requesting admin rights before continuing (the default Windows screen that asks if user wants to run as administrator)

**Comment by sallar** [comment] 2019-02-02 10:08
Hi, thank you. But this is a dupe of #690. Closing in favour of that issue.

**Closed by sallar** 2019-02-02 10:08 UTC

**Comment by diguifi** [comment] 2019-02-02 11:14
I don't remember if that was the exact error I got, but probably. If I get a different error on the next update I'll post it there. Thank you!
