### ISSUE TITLE
Google drive connection issue

### ISSUE THREAD

**Issue by alexk136** [buttercup/buttercup-desktop#1154] opened 2022-07-28 05:04 UTC
I tried with:
Bittercup for android, 1 phone new installation not connecting, authentication ok, but then app hangs.
I tried download .AddImage latest for linux, buttercup::// not working, manual auth not working.
I tried install from Deepin Package manager:
1. error, module "tray" not found
2. buttercup::// not working.

Only old app on my old phone is working, so now i  almoust lost all my passwords. How can export them from google drive with android app or other way?

**Comment by perry-mitchell** [comment] 2022-08-11 17:29
You can export them using the desktop app. Download the .bcup file from your google drive to your local machine and add it to the desktop app. You can export from there.

I can't reproduce this unfortunately, so I'll close this issue.

**Closed by perry-mitchell** 2022-08-11 17:29 UTC
