### ISSUE TITLE
feature request: Reordering custom fields by drag and drop

### ISSUE THREAD

**Issue by william-sy** [buttercup/buttercup-desktop#1225] opened 2023-06-03 20:32 UTC
It would be nice to rearrange the custom fields in a specific order, and be able to do this by dragging and dropping 

Now if I put a url first and otp later I have to delete URL and recreate it under otp for this to work and rearrange items

**Comment by ldexterldesign** [comment] 2023-12-10 06:48
Duplicate of https://github.com/buttercup/buttercup-desktop/issues/301

If you agree then close this issue please

Hope this helps

Regards

**Closed** 2023-12-11 04:09 UTC
