### ISSUE TITLE
Can't use synced-archives (like on dropbox) offline

### ISSUE THREAD

**Issue by asosnovsky** [buttercup/buttercup-desktop#391] opened 2017-11-10 15:14 UTC
**Issue**:
After adding a new archive from Dropbox, it is impossible to use while offline. The following error shows up:
```
Error: Failed unlocking archive
Failed to unlock source with ID:
f24918db-***********************************
Failed mapping credentials to a source: 
Network request failed
```
(I omitted the ID, I am not sure what it is).

**Potential Solution**
Cache the current archive in an offline archive, and upon a connection merge the changes

**System**
OS: Ubuntu 16.04

P.S.
I get the same issue on the mobile app (android LG V20)

**Comment by sallar** [comment] 2017-11-10 16:31
Hi @asosnovsky, Thanks. This is a know issue and popular request. Closing this since it's a duplicate of #307

**Closed by sallar** 2017-11-10 16:31 UTC
