### ISSUE TITLE
Unhandled Promise Rejection : missing app-update.yml

### ISSUE THREAD

**Issue by GertVanKruiningen** [buttercup/buttercup-desktop#896] opened 2020-03-18 11:37 UTC
Hi, running on Ubuntu, every time I am entering the Master Password after starting up Buttercup for the first time, I get this error, I get the following Unhandled Promise Rejection error :
![unhandled promise rejection buttercup](https://user-images.githubusercontent.com/18393897/76956580-32a73680-6979-11ea-90be-91597fdd3dd0.png)

And it is correct that this file "app-update.yml" isn't there.
Also creating that file in the folder shown, doesn't fix the problem

Please help...

Cheers
Gert

**Comment by ghostd** [comment] 2020-03-18 12:30
Hi,

It seems to be a duplicate of #859

**Comment by Vinaum8** [comment] 2020-03-27 14:44
me too have this problem on ubuntu 18.04.4 LTS.

**Comment by perry-mitchell** [comment] 2020-04-19 12:53
Duplicate of #859 as @ghostd pointed out, closing.

**Closed by perry-mitchell** 2020-04-19 12:53 UTC
