### ISSUE TITLE
Cannot add a vault located on Google Drive

### ISSUE THREAD

**Issue by tigrouind** [buttercup/buttercup-desktop#1207] opened 2023-04-22 19:33 UTC
I can't add a vault located on a Google Drive. It works fine with version 2.18.2 but fails with version 2.19.0.

After opening the link created by Google, I am redirected to Buttercup and the following error message appears on the top left: 
> Google authentication failed: Failed to run 'fetch' on 'Window': Illegal invocation****

I removed Buttercup's authorization as suggested in [#1188](https://github.com/buttercup/buttercup-desktop/issues/1188) but it didn't help.

Additionally : it's possible to open a vault with 2.19.0 version if vault has been added before (eg: with 2.18.2) but synchronization fails silently : there is no error message but the changes are not saved.

I notified that Buttercup has created many "Untitled" files with "[object] [Object]" content in the root of my Google Drive account. It's probably due to failed synchronization.

**Comment by Asuniia** [comment] 2023-04-23 09:51
same issue 

`index.js:710 TypeError: Failed to execute 'fetch' on 'Window': Illegal invocation
    at I.exchangeAuthCodeForToken (index.js:912:1030011)
    at index.js:912:16313
    at Generator.next (<anonymous>)
    at o (index.js:912:14893)
(anonymous) @ index.js:710`

**Comment by perry-mitchell** [comment] 2023-04-24 06:31
Seems I'm not even able to authenticate Google Drive currently on prod 2.19.0, as Firefox won't open the auth code link -> Buttercup Desktop after I confirm permissions. This _was_ working before I published it.

I'll try to debug later today.. In the mean time please let me know what OSes you're using @tigrouind @Asuniia

**Comment by tigrouind** [comment] 2023-04-24 07:49
> Seems I'm not even able to authenticate Google Drive currently on prod 2.19.0, as Firefox won't open the auth code link -> Buttercup Desktop after I confirm permissions. This _was_ working before I published it.
> 
> I'll try to debug later today.. In the mean time please let me know what OSes you're using @tigrouind @Asuniia

The issue was initially discovered on Windows 11 22H2 but I can reproduce it on Windows 10 Pro 21H2.

**Comment by Asuniia** [comment] 2023-04-24 07:54
I use Windows 11 Pro 22H2

**Comment by perry-mitchell** [comment] 2023-04-24 16:50
> iPhone XR iOS 16.2 with Buttercup app same bug

Mobile has not been updated recently, so it's not related to this issue. At least for now.

**Comment by perry-mitchell** [comment] 2023-04-24 18:58
Going to close this as a dupe of #1200

**Closed by perry-mitchell** 2023-04-24 18:58 UTC
Labels: Status: Pending
