### ISSUE TITLE
Check for buttercup's archive existence

### ISSUE THREAD

**Issue by rezamarandi** [buttercup/buttercup-desktop#313] opened 2017-07-09 03:47 UTC
Hey guys,
I just wanna recommend to add new feature and check for BC's archive existence before show it in sidebar,
Because right now when i open my BC there is record sitting there for an old deleted archive.

**Comment by sallar** [comment] 2017-07-09 08:20
Hi @rezamarandi, This is being fixed in the next release.

**Comment by sallar** [comment] 2017-07-09 08:21
This is also a duplicate of #81. Closing this in favor of that one. Thanks!

**Closed by sallar** 2017-07-09 08:21 UTC
