### ISSUE TITLE
Update -> 1.2.2 error

### ISSUE THREAD

**Issue by fmommeja** [buttercup/buttercup-desktop#529] opened 2018-02-18 17:54 UTC
Hi, hile receiving the message annoucing the new update 1.2.2, I got this message:

```
Unhandled Promise Rejection
Error: La requête a expiré.
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (/Applications/Buttercup.app/Contents/Resources/app.asar/dist/app.js:71191:19)
    at new PromiseSpawn (/Applications/Buttercup.app/Contents/Resources/app.asar/dist/app.js:73161:17)
    at /Applications/Buttercup.app/Contents/Resources/app.asar/dist/app.js:73315:21
    at MacUpdater._checkForUpdates (/Applications/Buttercup.app/Contents/Resources/app.asar/dist/app.js:8335:11)
    at MacUpdater.checkForUpdates (/Applications/Buttercup.app/Contents/Resources/app.asar/dist/app.js:8281:39)
    at Timeout.checkForUpdates [as _onTimeout] (/Applications/Buttercup.app/Contents/Resources/app.asar/dist/app.js:31898:67)
```

and when I said OK to the update, Buttercup restarted without making the update.

Since then it's still in 1.2.1 and doesn't find an update anymore…

Mac OSX 10.9.5 Build 13F1911 - i7 2.8 GHz - 16 Go DDR3

Kind regards

-- 
Frederic

**Comment by sallar** [comment] 2018-02-18 17:58
Hi. this is a dupe of #517. closing in favor of that one. I'm going to try to focus on this next. Thanks :)

**Closed by sallar** 2018-02-18 17:58 UTC
