### ISSUE TITLE
[FR] Button to sync the vault with the remote storage

### ISSUE THREAD

**Issue by gravistech412** [buttercup/buttercup-desktop#1305] opened 2024-03-27 21:58 UTC
We share the vaults. Sometimes one of us updates an entry and needs to have the other person's vault updated. It would be good to have a button to re-sync the vault with the remote storage. Currently we need to wait for the vault to sync or lock/unlock.

**Comment by perry-mitchell** [comment] 2024-03-28 10:57
Dupe of #1226

**Closed by perry-mitchell** 2024-03-28 10:57 UTC
