### ISSUE TITLE
Error when adding meta

### ISSUE THREAD

**Issue by BlueBeniHD** [buttercup/buttercup-desktop#422] opened 2017-11-17 22:20 UTC
When I try to add a custom field this error appears: 

```
Unhandled Error
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at d (file:///C:/Program%20Files/Buttercup/resources/app.asar/dist/main.bundle.js:13448:2753)
    at s (file:///C:/Program%20Files/Buttercup/resources/app.asar/dist/main.bundle.js:13448:1399)
    at Function.o.from (file:///C:/Program%20Files/Buttercup/resources/app.asar/dist/main.bundle.js:13454:532)
    at Object.encodeStringValue (file:///C:/Program%20Files/Buttercup/resources/app.asar/dist/main.bundle.js:13454:70036)
    at Object.wrap (file:///C:/Program%20Files/Buttercup/resources/app.asar/dist/main.bundle.js:13454:75198)
    at i.addArgument (file:///C:/Program%20Files/Buttercup/resources/app.asar/dist/main.bundle.js:13454:74667)
    at u.setMeta (file:///C:/Program%20Files/Buttercup/resources/app.asar/dist/main.bundle.js:13460:41426)
    at meta.forEach.metaObj (file:///C:/Program%20Files/Buttercup/resources/app.asar/dist/main.bundle.js:75731:13)
    at Object.updateEntry [as e] (file:///C:/Program%20Files/Buttercup/resources/app.asar/dist/main.bundle.js:75728:8)
```

But I can edit already created Fields without an error

Please Help me!

**Comment by perry-mitchell** [comment] 2017-11-17 22:29
Hi @BlueBeniHD - Can you confirm that you're on the latest version? Please try a full restart of the application and try again, if you wouldn't mind. I can't reproduce this on Mac, so I wonder if what you're experiencing is a windows issue.

**Comment by perry-mitchell** [comment] 2017-11-17 22:30
@sallar The `at u.setMeta` seems to be when the meta is getting set.. Perhaps verification is failing here..?

**Comment by perry-mitchell** [comment] 2017-11-17 22:32
At very least this error message shouldn't appear, so I'm marking this as a bug.

**Comment by BlueBeniHD** [comment] 2017-11-17 22:33
Hi, @perry-mitchell Yes I'm on the latest version v.0.24.1.
I'm on Windows, but on my Mac, there is the same issue.

**Comment by perry-mitchell** [comment] 2017-11-17 22:35
Ok.. Let's see if we can't narrow this down. Could you please walk me through the exact steps you take to reproduce the error?

A video/gif recording of you recreating the issue would be extremely helpful also.

**Comment by BlueBeniHD** [comment] 2017-11-17 22:36
@perry-mitchell I'll be doing this, give me a minute.

**Comment by perry-mitchell** [comment] 2017-11-17 22:40
@BlueBeniHD It's quite late here in Helsinki, so if I don't get a chance to look at this tonight I'll continue first thing.

**Comment by BlueBeniHD** [comment] 2017-11-17 22:41
@perry-mitchell Maby its important that I'm connected via OwnCloud.
I'm coming from Austria, it's also late here.

**Comment by ph1p** [comment] 2017-11-18 00:20
@BlueBeniHD I've fixed this error in my latest PR(#400). It's already merged and labeled with "Needs release".

**Comment by sallar** [comment] 2017-11-18 08:53
@BlueBeniHD @perry-mitchell @ph1p We will release a new version today, we can close this after @BlueBeniHD can confirm that it's gone in that version. I'll update here when the version is out.

**Comment by BlueBeniHD** [comment] 2017-11-18 11:25
@perry-mitchell @sallar @ph1p in v0.24.2 the issue is fully gone, thank you for your quick support!

**Comment by sallar** [comment] 2017-11-18 11:51
@BlueBeniHD glad to know :) closing this 👍

**Closed by sallar** 2017-11-18 11:51 UTC
Labels: Platform: Windows, Priority: High, Type: Bug
