### ISSUE TITLE
Showing errors

### ISSUE THREAD

**Issue by regoremor** [buttercup/buttercup-desktop#472] opened 2017-12-20 22:02 UTC
Unhandled Error
Error: net::ERR_CONNECTION_RESET

**Comment by regoremor** [comment] 2017-12-20 22:04
Unhandled Promise Rejection
Error: The request timed out.
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (/Applications/Buttercup.app/Contents/Resources/app.asar/dist/app.js:71297:19)
    at new PromiseSpawn (/Applications/Buttercup.app/Contents/Resources/app.asar/dist/app.js:73267:17)
    at /Applications/Buttercup.app/Contents/Resources/app.asar/dist/app.js:73421:21
    at MacUpdater._checkForUpdates (/Applications/Buttercup.app/Contents/Resources/app.asar/dist/app.js:8884:11)
    at MacUpdater.checkForUpdates (/Applications/Buttercup.app/Contents/Resources/app.asar/dist/app.js:8830:39)
    at checkForUpdates (/Applications/Buttercup.app/Contents/Resources/app.asar/dist/app.js:31839:67)
    at startAutoUpdate (/Applications/Buttercup.app/Contents/Resources/app.asar/dist/app.js:31829:3)
    at setupActions (/Applications/Buttercup.app/Contents/Resources/app.asar/dist/app.js:95742:82)
    at App.<anonymous> (/Applications/Buttercup.app/Contents/Resources/app.asar/dist/app.js:37011:74)
    at Generator.next (<anonymous>)
    at step (/Applications/Buttercup.app/Contents/Resources/app.asar/dist/app.js:36892:191)
    at /Applications/Buttercup.app/Contents/Resources/app.asar/dist/app.js:36892:361
    at <anonymous>

**Comment by sallar** [comment] 2017-12-21 20:45
Thanks @regoremor this is a dupe of #416 so I'll close this in favor of that. We'll try to look into it soon.

**Closed by sallar** 2017-12-21 20:45 UTC
