### ISSUE TITLE
The title and search are not supported in Chinese

### ISSUE THREAD

**Issue by oopo0** [buttercup/buttercup-desktop#1032] opened 2021-05-11 23:15 UTC
Hi:
The title and search are not supported in Chinese.

Thank you !

**Comment by perry-mitchell** [comment] 2021-05-17 18:55
I'll have a look for these, but in the meantime could you please screenshot+highlight the items you've noticed are not translated? Thank you..

**Comment by fmommeja** [comment] 2021-05-19 08:09
Hi @perry-mitchell 
at least, here are the items not translated in **French** _(I guess it's similar in Chinese)_:

![Buttercup-translate1](https://user-images.githubusercontent.com/19188155/118778099-0e4f2e80-b88a-11eb-8e01-e5e977a450aa.jpg)

![Buttercup-translate2](https://user-images.githubusercontent.com/19188155/118778164-1a3af080-b88a-11eb-9e78-43f86bc72c72.jpg)

![Buttercup-translate3](https://user-images.githubusercontent.com/19188155/118778195-232bc200-b88a-11eb-882d-d61f2435ded0.jpg)

**Comment by julianpoemp** [comment] 2021-05-19 08:39
@fmommeja same with German.

btw this is a duplicate of #999

**Comment by fmommeja** [comment] 2021-05-19 08:42
Hi @julianpoemp I saw that…
That's why, a few minutes ago, I already added a link to this one in [#999](https://github.com/buttercup/buttercup-desktop/issues/999)!  ;)

**Comment by perry-mitchell** [comment] 2021-05-21 05:11
Thanks everyone - I'll close in favour of #999 and will try to get the fixes done asap.

**Closed by perry-mitchell** 2021-05-21 05:11 UTC
