### ISSUE TITLE
Unhandled Error (Dropbox source)

### ISSUE THREAD

**Issue by Ravenheart** [buttercup/buttercup-desktop#321] opened 2017-08-18 06:10 UTC
Tried adding two custom fields to an entry and received the said error. The error appears to happen at some point when the .bcup archive is being saved or some caches are being flushed to it.

"TypeError: e.replace is not a function"
![buttercup](https://user-images.githubusercontent.com/853378/29446418-c6044e30-83f4-11e7-807f-119fbca915d4.PNG)

**Comment by Ravenheart** [comment] 2017-08-18 07:02
After some more testing I can conclude its happening when I use the Dropbox integration (ie "Load from Cloud Services" archive).

**Comment by sallar** [comment] 2017-08-19 10:33
Thanks @Ravenheart, we'll look into it.

**Comment by sallar** [comment] 2017-09-16 11:02
Hi @Ravenheart, is there a way to reproduce this? I tried adding custom fields to my dropbox archive, but it saves normally and doesn't throw any errors.

**Comment by Ravenheart** [comment] 2017-09-16 11:55
It happened when i opened a cloud archive in dropbox and added those custom fields, will see if i can repro it with a clean archive monday.

**Comment by sallar** [comment] 2017-10-07 18:52
Hey @Ravenheart, hope you're having a nice weekend. Were you able to reproduce the issue or should we close this for now?

**Comment by perry-mitchell** [comment] 2017-10-10 17:49
I'll close this due to inactivity. If it's still occurring we can of course re-open it.

**Closed by perry-mitchell** 2017-10-10 17:49 UTC
Labels: Priority: High, Status: Available, Type: Bug
