### ISSUE TITLE
incorrect output of the database name

### ISSUE THREAD

**Issue by wormen** [buttercup/buttercup-desktop#1189] opened 2023-02-03 09:15 UTC
Windows 10
![image](https://user-images.githubusercontent.com/8462339/216559956-681e0d6e-ffd3-4361-8c8b-0af9123f50a7.png)

the same local database connected in Ubuntu 22.04
![image](https://user-images.githubusercontent.com/8462339/216560228-5660785b-b24e-47cd-a5e3-dbb306e22fe1.png)

**Comment by perry-mitchell** [comment] 2023-03-05 16:14
To confirm, you're adding it, in both cases, via the local file system?

I'm a bit skeptical that you are, as the second appears to be a Google Drive ID.

**Comment by wormen** [comment] 2023-03-05 17:13
in both cases, the bases were connected in the same way

**Comment by perry-mitchell** [comment] 2023-05-12 04:14
I can't reproduce this. Also as mentioned, that second image shows a Google Drive ID.. so I'm not sure what it has to do with local vaults. I'll close this until some kind of reproduction steps can be provided.

**Closed by perry-mitchell** 2023-05-12 04:14 UTC
