### ISSUE TITLE
Enharncement Request - change vault password or export to new vault

### ISSUE THREAD

**Issue by p-sims** [buttercup/buttercup-desktop#1151] opened 2022-07-14 13:16 UTC
I useful improvement would be to able to change vault password or be able to export vault content with a new password. As far as I'm aware, currently the only way to do this is to export to plain text CSV and then re-import to new vault. If your trying to keep the contents encrypted would it not be better to be able to re-encrypt content of an unlocked vault within buttercup without creating plain text copies in file system?

This could be via a change password options when a vault is unlocked. Or it could be via an export option which creates new vault with new password.

I could work out how to tag this as an enhancement, but it's clearly low priority.

Thanks,

**Comment by perry-mitchell** [comment] 2022-07-27 18:53
Yes, definitely needed. Dupe of #1046

**Closed by perry-mitchell** 2022-07-27 18:53 UTC
