### ISSUE TITLE
[Feature Request] Expiration Date for entries

### ISSUE THREAD

**Issue by pelonchasva** [buttercup/buttercup-desktop#1148] opened 2022-07-06 19:42 UTC
Hi,

I tried to find this issue in the list, but none popped up.

I would like to request an option to set an **Expiration date** for entries, this functionality is useful because there are some websites or apps that have a policy to continuously update passwords.

Some companies or work related accounts also have the same policy, this functionality is present in other password managers such as KeePassXC.

![image](https://user-images.githubusercontent.com/4713147/177629987-8f1311b2-c812-4d4f-a845-cacb22094b7c.png)

Are there any plans for this functionality or has it been brought before?

**Comment by perry-mitchell** [comment] 2022-08-11 17:25
Agreed, but dupe of this: https://github.com/buttercup/buttercup-core/issues/163

**Closed by perry-mitchell** 2022-08-11 17:25 UTC
