### ISSUE TITLE
[FEAT REQ] General search bar

### ISSUE THREAD

**Issue by jgtoriginal** [buttercup/buttercup-desktop#526] opened 2018-02-17 17:29 UTC
There's a search bar directory based, but I there's no way to search across all groups for a single credential. So as I got more than 20 groups, with more than 10 credentials each, some of which correspond to the same services, I need to go manually group by group in order to search something.
I know this might be a very frequent case among sysadmins, and maybe not as urgent for final users, but still would be a very big enhancement.

**Comment by sallar** [comment] 2018-02-17 20:32
Thanks! This is a dupe of #314 and #136. Closing this in favor of those :)

**Closed by sallar** 2018-02-17 20:32 UTC

**Comment by jgtoriginal** [comment] 2018-02-17 20:53
my bad bad I didn't check if that was the case before posting. sorry about that!
