### ISSUE TITLE
Error on checking for update 

### ISSUE THREAD

**Issue by tmotyl** [buttercup/buttercup-desktop#873] opened 2019-12-20 12:43 UTC
on ubuntu 19.10, installed via .deb
open buttercup, go to "system->check for updates"

![image](https://user-images.githubusercontent.com/515397/71255549-749aef00-232e-11ea-9628-6a69f06e177b.png)

In the log:
[2019-12-20 13:40:43.059] [info] Checking for update
[2019-12-20 13:40:43.060] [error] Error: Error: ENOENT: no such file or directory, open '/opt/Buttercup/resources/app-update.yml'

**Comment by ghostd** [comment] 2019-12-20 12:56
Hi

Duplicate of #859 ?

**Closed** 2019-12-20 17:51 UTC
