### ISSUE TITLE
Android App Fails to Connect to WebDAV

### ISSUE THREAD

**Issue by ckauth97** [buttercup/buttercup-desktop#914] opened 2020-05-18 14:41 UTC
When attempting to add a vault via WebDAV on Android, an error banner pops up saying there is a network issue and prevents connection.

This occurs over VPN and on the same network as the hosted server.

Using an HTTP connection as a trial run, haven't had the chance to try HTTPS (will update issue if the latter works).

**Comment by stuartm** [comment] 2020-09-14 11:28
I'm facing the same issue with 1.20.5

The webdav server is local, on the same network and uses http. Since I only ever intend connecting remotely via VPN and this server isn't internet facing I don't see myself using https since that then requires messing about adding custom CA certs to Android. Although like the OP I wonder if this might be the route of the issue because the app assumes https?

The Remote URL has the protocol specified (note - desktop app quietly fails with no useful error if this is missing).

Even if there are no plans to fix this, it would be good to get a clear answer on this. At the very least if http is the problem and it won't be supported, an appropriate error message is needed.

**Comment by perry-mitchell** [comment] 2021-02-20 21:41
Sorry for the terribly late response.. Most likel;y too late, but I'll answer regardless.

The app doesn't care about HTTP/HTTPS - or at least it shouldn't. It will fail to access HTTPS resources that do not have a valid public certificate though. I'm sure there could be improvements made to the connection process, and I would happily accept a PR if you are able to debug the issue. Unfortunately we don't have time to debug this one ourselves, and probably couldn't reproduce your exact environment anyhow.

**Closed** 2021-04-05 18:28 UTC
Labels: Status: Revision Needed

**Comment by karpiCz** [comment] 2023-01-08 20:11
Hello there is probably the same problem for me. Trying to connect synology webdav server from android on local net and red message appears:
"Connection failed
webDAV connection test failed"
The same behavior for http and https setup.
On the server side no login attempt loged.
For windows buttercup client connection successful. 
version 2.5.2

**Comment by owlysk** [comment] 2023-12-20 20:14
Same here
