### ISSUE TITLE
Windows 10: update procedure does not work

### ISSUE THREAD

**Issue by julianpoemp** [buttercup/buttercup-desktop#805] opened 2019-09-04 18:01 UTC
### Problem
The update to 1.16.2 failed on my Windows 10 PC. After some time, I got an "EACCESS" error or something like that. I can't reproduce it, because I already found a workaround: If buttercup is run as admin, the update works.

### Suggestion:
I think buttercup should be run as administrator permanently. Could you implement it so that this issue is fixed for all windows users?

**Comment by perry-mitchell** [comment] 2019-09-05 19:29
The problem is that Buttercup shouldn't need admin rights - it does nothing that warrants access to secure portions of the filesystem, or makes any system-level changes, etc..

It launches a local server for browser-extension connectivity, but this doesn't require administration. It can provide a tray icon, but this shouldn't require administration. I can't think of a single reason why admin access would be remotely necessary. I believe that forcing admin privileges would be a bandaid on the larger issue, which we don't know yet.

Buttercup is a standard user-level application that doesn't need anything administrator access has to offer, in my opinion.

**Comment by julianpoemp** [comment] 2019-09-06 08:34
> I think we can still describe this whole thing as a bug: And the more people look at it, like you've said, the more it seems like it's the update process itself. We're planning on possibly killing it because of this exact issue.

I don't think you have to kill this feature. Perhaps you need another update workflow. Something what other desktop applications do:

1. Download new version as installer
2. Run installer as admin and close current Buttercup
3. Open Buttercup after installation

That does the owncloud client, too. It's normal that installations need admin rights, MacOSX asks for it, too.

**Comment by perry-mitchell** [comment] 2019-09-09 18:04
Well I didn’t mean kill the update system altogether, merely the one we’re using.

**Comment by karousn** [comment] 2019-10-18 06:10
the same here , i got a [message error](https://gist.github.com/karousn/90cdbbbd77c24e88dd80e01f71426eab)

**Comment by ttamminen** [comment] 2019-10-20 16:21
Hey @perry-mitchell, I think I am receiving the same error as @karousn 

```
Unhandled Promise Rejection
Error: New version 1.17.0 is not signed by the application owner: publisherNames: COMODO RSA Code Signing CA, raw info: {
  "SignerCertificate": {
    "FriendlyName": "",
    "IssuerName": {
      "Name": "CN=COMODO RSA Code Signing CA, O=COMODO CA Limited, L=Salford, S=Greater Manchester, C=GB",
      "Oid": "System.Security.Cryptography.Oid"
    },
    "NotAfter": "/Date(1578009599000)/",
    "NotBefore": "/Date(1546387200000)/",
    "PrivateKey": null,
    "PublicKey": {
      "Key": "System.Security.Cryptography.RSACryptoServiceProvider",
      "Oid": "System.Security.Cryptography.Oid",
      "EncodedKeyValue": "System.Security.Cryptography.AsnEncodedData",
      "EncodedParameters": "System.Security.Cryptography.AsnEncodedData"
    },
    "SerialNumber": "00BDC2D8815A5B41D6045C6C719D8A8F2A",
    "SignatureAlgorithm": {
      "Value": "1.2.840.113549.1.1.11",
      "FriendlyName": "sha256RSA"
    },
    "Thumbprint": "A9C56AD137B3A5359A375A1FA4827DDD071A845A",
    "Version": 3,
    "Issuer": "CN=COMODO RSA Code Signing CA, O=COMODO CA Limited, L=Salford, S=Greater Manchester, C=GB",
    "Subject": "CN=MadDev Oy, O=MadDev Oy, STREET=N�kinkaari 4 A, L=Espoo, S=Uusimaa, PostalCode=02320, C=FI"
  },
  "TimeStamperCertificate": {
    "Archived": false,
    "Extensions": [
      "System.Security.Cryptography.X509Certificates.X509KeyUsageExtension",
      "System.Security.Cryptography.X509Certificates.X509BasicConstraintsExtension",
      "System.Security.Cryptography.X509Certificates.X509EnhancedKeyUsageExtension",
      "System.Security.Cryptography.X509Certificates.X509Extension",
      "System.Security.Cryptography.X509Certificates.X509Extension",
      "System.Security.Cryptography.X509Certificates.X509SubjectKeyIdentifierExtension",
      "System.Security.Cryptography.X509Certificates.X509Extension",
      "System.Security.Cryptography.X509Certificates.X509Extension"
    ],
    "FriendlyName": "",
    "IssuerName": {
      "Name": "CN=DigiCert Assured ID CA-1, OU=www.digicert.com, O=DigiCert Inc, C=US",
      "Oid": "System.Security.Cryptography.Oid"
    },
    "NotAfter": "/Date(1729555200000)/",
    "NotBefore": "/Date(1413936000000)/",
    "HasPrivateKey": false,
    "PrivateKey": null,
    "PublicKey": {
      "Key": "System.Security.Cryptography.RSACryptoServiceProvider",
      "Oid": "System.Security.Cryptography.Oid",
      "EncodedKeyValue": "System.Security.Cryptography.AsnEncodedData",
      "EncodedParameters": "System.Security.Cryptography.AsnEncodedData"
    },
    "SerialNumber": "03019A023AFF58B16BD6D5EAE617F066",
    "SubjectName": {
      "Name": "CN=DigiCert Timestamp Responder, O=DigiCert, C=US",
      "Oid": "System.Security.Cryptography.Oid"
    },
    "SignatureAlgorithm": {
      "Value": "1.2.840.113549.1.1.5",
      "FriendlyName": "sha1RSA"
    },
    "Thumbprint": "614D271D9102E30169822487FDE5DE00A352B01D",
    "Version": 3,
    "Handle": 2850618952336,
    "Issuer": "CN=DigiCert Assured ID CA-1, OU=www.digicert.com, O=DigiCert Inc, C=US",
    "Subject": "CN=DigiCert Timestamp Responder, O=DigiCert, C=US"
  },
  "Status": 0,
  "StatusMessage": "Signature verified."
}
    at t.newError (C:/Program Files/Buttercup/resources/app.asar/dist/app.js:1:8496)
    at Object.<anonymous> (C:/Program Files/Buttercup/resources/app.asar/dist/app.js:207:228505)
    at Generator.next (<anonymous>)
    at Generator.c (C:/Program Files/Buttercup/resources/app.asar/dist/app.js:1:1411)
    at d._promiseFulfilled (C:/Program Files/Buttercup/resources/app.asar/dist/app.js:206:189112)
    at j._settlePromise (C:/Program Files/Buttercup/resources/app.asar/dist/app.js:206:145545)
    at j._settlePromise0 (C:/Program Files/Buttercup/resources/app.asar/dist/app.js:206:146143)
    at j._settlePromises (C:/Program Files/Buttercup/resources/app.asar/dist/app.js:206:147495)
    at d (C:/Program Files/Buttercup/resources/app.asar/dist/app.js:206:149218)
    at p (C:/Program Files/Buttercup/resources/app.asar/dist/app.js:206:149157)
    at s._drainQueues (C:/Program Files/Buttercup/resources/app.asar/dist/app.js:206:150677)
    at Immediate.drainQueues [as _onImmediate] (C:/Program Files/Buttercup/resources/app.asar/dist/app.js:206:148899)
From previous event:
    at j.z [as _captureStackTrace] (C:/Program Files/Buttercup/resources/app.asar/dist/app.js:206:164744)
    at new d (C:/Program Files/Buttercup/resources/app.asar/dist/app.js:206:187987)
    at C:/Program Files/Buttercup/resources/app.asar/dist/app.js:206:191076
    at t.NsisUpdater.downloadUpdate (C:/Program Files/Buttercup/resources/app.asar/dist/app.js:71:20764)
    at EventEmitter.i.ipcMain.on (C:/Program Files/Buttercup/resources/app.asar/dist/app.js:414:129520)
    at WebContents.<anonymous> (C:/Program Files/Buttercup/resources/electron.asar/browser/api/web-contents.js:285:13)
```

**Comment by sallar** [comment] 2019-10-20 19:38
Thanks everyone. I did sign the executable but this time I signed it on a Windows machine (I always sign it on a mac). Seems like it hasn't worked correctly (even though I verified it again and it seemed to be ok... I will investigate. Sorry for the inconvenience.

**Comment by sallar** [comment] 2019-10-20 20:16
Can everyone please check to see if the issue is resolved? I deleted and re-uploaded a new version of signed windows files.

**Comment by karousn** [comment] 2019-10-21 06:26
```
Unhandled Error
Error: spawn C:/Users/nkarous/AppData/Local/Temp/up-8ycbpR/buttercup-desktop-setup-1.17.0.exe EACCES
```
I think because i should have admin access to install something on my work machine.
at least show me the promp windows to logging as admin to achive the update (like many other program as virtualbox .. do when we update them)

**Comment by ttamminen** [comment] 2019-10-21 06:38
I get the same error as before.

```
Unhandled Promise Rejection
Error: New version 1.17.0 is not signed by the application owner:
publisherNames: COMODO RSA Code Signing CA, raw info: {
  "SignerCertificate": {
    "FriendlyName": "",
    "IssuerName": {
      "Name": "CN=COMODO RSA Code Signing CA, O=COMODO CA Limited,
L=Salford, S=Greater Manchester, C=GB",
      "Oid": "System.Security.Cryptography.Oid"
    },
    "NotAfter": "/Date(1578009599000)/",
    "NotBefore": "/Date(1546387200000)/",
    "PrivateKey": null,
    "PublicKey": {
      "Key": "System.Security.Cryptography.RSACryptoServiceProvider",
      "Oid": "System.Security.Cryptography.Oid",
      "EncodedKeyValue": "System.Security.Cryptography.AsnEncodedData",
      "EncodedParameters": "System.Security.Cryptography.AsnEncodedData"
    },
    "SerialNumber": "00BDC2D8815A5B41D6045C6C719D8A8F2A",
    "SignatureAlgorithm": {
      "Value": "1.2.840.113549.1.1.11",
      "FriendlyName": "sha256RSA"
    },
    "Thumbprint": "A9C56AD137B3A5359A375A1FA4827DDD071A845A",
    "Version": 3,
    "Issuer": "CN=COMODO RSA Code Signing CA, O=COMODO CA Limited,
L=Salford, S=Greater Manchester, C=GB",
    "Subject": "CN=MadDev Oy, O=MadDev Oy, STREET=N�kinkaari 4 A, L=Espoo,
S=Uusimaa, PostalCode=02320, C=FI"
  },
  "TimeStamperCertificate": {
    "Archived": false,
    "Extensions": [
      "System.Security.Cryptography.X509Certificates.X509KeyUsageExtension",

"System.Security.Cryptography.X509Certificates.X509BasicConstraintsExtension",

"System.Security.Cryptography.X509Certificates.X509EnhancedKeyUsageExtension",
      "System.Security.Cryptography.X509Certificates.X509Extension",
      "System.Security.Cryptography.X509Certificates.X509Extension",

"System.Security.Cryptography.X509Certificates.X509SubjectKeyIdentifierExtension",
      "System.Security.Cryptography.X509Certificates.X509Extension",
      "System.Security.Cryptography.X509Certificates.X509Extension"
    ],
    "FriendlyName": "",
    "IssuerName": {
      "Name": "CN=DigiCert Assured ID CA-1, OU=www.digicert.com, O=DigiCert
Inc, C=US",
      "Oid": "System.Security.Cryptography.Oid"
    },
    "NotAfter": "/Date(1729555200000)/",
    "NotBefore": "/Date(1413936000000)/",
    "HasPrivateKey": false,
    "PrivateKey": null,
    "PublicKey": {
      "Key": "System.Security.Cryptography.RSACryptoServiceProvider",
      "Oid": "System.Security.Cryptography.Oid",
      "EncodedKeyValue": "System.Security.Cryptography.AsnEncodedData",
      "EncodedParameters": "System.Security.Cryptography.AsnEncodedData"
    },
    "SerialNumber": "03019A023AFF58B16BD6D5EAE617F066",
    "SubjectName": {
      "Name": "CN=DigiCert Timestamp Responder, O=DigiCert, C=US",
      "Oid": "System.Security.Cryptography.Oid"
    },
    "SignatureAlgorithm": {
      "Value": "1.2.840.113549.1.1.5",
      "FriendlyName": "sha1RSA"
    },
    "Thumbprint": "614D271D9102E30169822487FDE5DE00A352B01D",
    "Version": 3,
    "Handle": 2562524665808,
    "Issuer": "CN=DigiCert Assured ID CA-1, OU=www.digicert.com, O=DigiCert
Inc, C=US",
    "Subject": "CN=DigiCert Timestamp Responder, O=DigiCert, C=US"
  },
  "Status": 0,
  "StatusMessage": "Signature verified."
}
    at t.newError (C:/Program
Files/Buttercup/resources/app.asar/dist/app.js:1:8496)
    at Object.<anonymous> (C:/Program
Files/Buttercup/resources/app.asar/dist/app.js:207:228505)
    at Generator.next (<anonymous>)
    at Generator.c (C:/Program
Files/Buttercup/resources/app.asar/dist/app.js:1:1411)
    at d._promiseFulfilled (C:/Program
Files/Buttercup/resources/app.asar/dist/app.js:206:189112)
    at j._settlePromise (C:/Program
Files/Buttercup/resources/app.asar/dist/app.js:206:145545)
    at j._settlePromise0 (C:/Program
Files/Buttercup/resources/app.asar/dist/app.js:206:146143)
    at j._settlePromises (C:/Program
Files/Buttercup/resources/app.asar/dist/app.js:206:147495)
    at d (C:/Program
Files/Buttercup/resources/app.asar/dist/app.js:206:149218)
    at p (C:/Program
Files/Buttercup/resources/app.asar/dist/app.js:206:149157)
    at s._drainQueues (C:/Program
Files/Buttercup/resources/app.asar/dist/app.js:206:150677)
    at Immediate.drainQueues [as _onImmediate] (C:/Program
Files/Buttercup/resources/app.asar/dist/app.js:206:148899)
From previous event:
    at j.z [as _captureStackTrace] (C:/Program
Files/Buttercup/resources/app.asar/dist/app.js:206:164744)
    at new d (C:/Program
Files/Buttercup/resources/app.asar/dist/app.js:206:187987)
    at C:/Program Files/Buttercup/resources/app.asar/dist/app.js:206:191076
    at t.NsisUpdater.downloadUpdate (C:/Program
Files/Buttercup/resources/app.asar/dist/app.js:71:20764)
    at EventEmitter.i.ipcMain.on (C:/Program
Files/Buttercup/resources/app.asar/dist/app.js:414:129520)
    at WebContents.<anonymous> (C:/Program
Files/Buttercup/resources/electron.asar/browser/api/web-contents.js:285:13)
```

**Comment by julianpoemp** [comment] 2019-10-21 11:27
I'm quite sure, that my problem is not related to the signature issue, because my problem already existed with 1.16.2 and was caused by missing admin rights. The signature issue is another one that happens with 1.17.0, related with #826 .

**Comment by tertortoise** [comment] 2019-10-24 07:11
The same issue on win10 - unhandled promise rejection, new verision 1.17.2 is not signed by owner (I am on 1.16.2 now).

**Comment by ckadluba** [comment] 2019-11-04 08:57
Probably it is the same issue as this one here. 
https://github.com/electron-userland/electron-builder/issues/3667

Have you tried setting the "publisherName" in package.json? This seemed to help in one case.
https://github.com/electron-userland/electron-builder/issues/3667#issuecomment-463227859

**Comment by sallar** [comment] 2019-11-04 15:54
Hi everyone. I understand this is becoming a big issue, but I just merged a PR that might fixed this. Thanks to @ckadluba. I'm going to try and re-release the same version to see if this issue will go away.

**Comment by tertortoise** [comment] 2019-11-13 07:13
Hi, my update issue seems to be over. I downloaded .exe file from the site and run install. It installed OK and now I am on 1.17.2. Still, when just before that I'd tried to upgrade from within an open app - it had failed with the same issue (unhandled promise rejection).

**Comment by ckadluba** [comment] 2019-11-15 10:29
> Hi everyone. I understand this is becoming a big issue, but I just merged a PR that might fixed this. Thanks to @ckadluba. I'm going to try and re-release the same version to see if this issue will go away.

Too bad this didn't help. :(.

**Comment by perry-mitchell** [comment] 2019-11-17 18:51
Let's try to keep this item on topic - #826 is for the certificates issue, and this is for the update process w/ admin rights. Thanks everyone.

**Comment by sallar** [comment] 2019-11-24 11:50
Hi everyone. I have tried to upgrade electron and electron-updater to see if things improve or not. I have forked buttercup to my own personal account and release a few test versions for testing this issue. Would you mind uninstalling the current Buttercup on your Windows, and installing this version:
https://github.com/sallar/buttercup-desktop/releases/download/v1.21.0/Buttercup-Setup-1.21.0.exe
To see if it auto updates correctly to v1.22.0?
Please dont forget to uninstall it again after the test, as the versions are not correct for the official releases.

Thank you!

**Comment by julianpoemp** [comment] 2019-11-24 12:18
@sallar I tested it just now on my windows pc. It works very well, thank you! (Windows 10 Pro, 64bit)

**Closed** 2019-11-25 17:15 UTC
Labels: Platform: Windows, Priority: High, Status: Help Wanted, Type: Bug
