### ISSUE TITLE
when I click on never mind I see this error

### ISSUE THREAD

**Issue by zoheirkhonyagar** [buttercup/buttercup-desktop#331] opened 2017-09-07 12:31 UTC
![sallar](https://user-images.githubusercontent.com/21988949/30163421-2ae1fa7e-93ee-11e7-917a-097251cb1c78.jpg)

**Comment by perry-mitchell** [comment] 2017-09-07 13:15
Duplicate of #329, so I'll close this one.

**Closed by perry-mitchell** 2017-09-07 13:15 UTC
