### ISSUE TITLE
Unable to "Add Archive" - build: v1.20.5 APPIMAGE, OS:  Fedora 33 (Workstation Edition) 64-bit

### ISSUE THREAD

**Issue by matthewdunsdon** [buttercup/buttercup-desktop#978] opened 2021-03-05 10:21 UTC
#### Reproduction steps

As a first time user:
1. Launch `./Buttercup-1.20.5.AppImage` from command line (frrom inside user home directory)
1. Wait for app to show
1. Try to create `New archive`
   1. either from "Welcome to Buttercup" panel - ``+ ADD ARCHIVE ->  New Archive File``
   1. or from via menu ``File -> New archive``
1. See native file window where I can choose directory and enter name for file
1. Choose directory within my user's home directory, give it a simple file name i.e. "test" and click "Save"

#### Expectations
- To see steps to progress with creating archive
- To see file on file system showing the archive
- To see error message in UI or terminal if error occurred.

#### Observed behaviour
* File window disappears and just see "Welcome to Buttercup" panel
* No messages in UI or terminal showing anything went wrong.

### Additional context
* Tried running `./Buttercup-1.20.5.AppImage --debug --verbose` to see if I would get more log messages, however that did not help
* Looked at `~/.config/Buttercup/log.log` to check for any errors, but that did not help
* I am a developer with js / typescript experience, in case you have any tips for me to try and debug / diagnose what the issue could be
*  Did try and "Toggle dev tools" and "Reload" to see if I could see any errors there, but that did not help.

**Comment by quietmansoath** [comment] 2021-03-07 02:04
Exact same issue, Pop! OS (ubuntu 20.10). Used the GUI though.

**Comment by GamesTrap** [comment] 2021-03-07 11:09
I was able to create a new archive by adding ".bcup" as the file ending for the new archive inside the file creation window.
Hope this can help you :)

**Comment by matthewdunsdon** [comment] 2021-03-12 11:24
I was able to resolve the issue by following the steps documented by @GamesTrap.

**Comment by matthewdunsdon** [comment] 2021-03-12 11:26
Are there any next actions worth taking from this?
- I can take a look at code base to see if there is a particular bug causing this.
- Do we want to investigate if a better user experience is possible here?

**Comment by perry-mitchell** [comment] 2021-03-17 20:58
Closing as a dupe of #955

**Closed by perry-mitchell** 2021-03-17 20:58 UTC
