### ISSUE TITLE
Dropbox sync: Opened file in IOS and Desktop fails to open (master password incorrect)

### ISSUE THREAD

**Issue by nahue** [buttercup/buttercup-desktop#606] opened 2018-05-09 13:23 UTC
Had buttercup-password working liked a charm! But then i installed it on my iPhone, added my dropbox file. And suddenly desktop fails to authenticate the master password. What can i do to help you debug this issue?

**Comment by perry-mitchell** [comment] 2018-05-09 14:42
Unfortunately not much. You can’t exactly share your archive with us. If you make a change and save it on mobile, does it then work on desktop?

**Comment by nahue** [comment] 2018-05-09 14:56
Tried it with no luck :( maybe a mismatch between encryption? maybe desktop and mobile use different versions of the encrypt module (im just a developer trying to guess)

**Comment by perry-mitchell** [comment] 2018-05-09 19:48
Encryption is the same - one of the features is interchangeable archives between apps.

This most likely is a reoccurring issue we have with encryption on mobile devices (a bug). Unfortunately there is no quick fix. We’ll be migrating to AES-GCM encryption in the coming months, and this is expected to resolve the problem.

**Comment by wxkylem** [comment] 2018-05-29 23:35
Was there any other solutions to this problem? I completely uninstalled and  updated to 1.7 but am still not able to access my repo.

**Comment by wxkylem** [comment] 2018-06-06 23:07
@sallar I just wanted to let you know that I was able to solve my problem. By using my phone's butter cup app I temporary removed a password. That updated the dropbox file and allowed my computer app to start working again. I am not sure if the issue is with the dropbox sync or some wierd bug with buttercup.  Thanks for your quick response the other day though!

**Comment by sallar** [comment] 2018-06-07 11:14
@wxkylem Thanks for checking this. Then this is related to the ongoing issue on mobile: https://github.com/buttercup/buttercup-mobile/issues/78
I'll close this and we can track the progress there!

**Closed by sallar** 2018-06-07 11:14 UTC
