### ISSUE TITLE
Biometric unlock option is grayed out in Windows

### ISSUE THREAD

**Issue by pdwonline** [buttercup/buttercup-desktop#1192] opened 2023-03-09 09:16 UTC
Biometric unclock works flawless on my phone, but not on Windows. It is essential in order to enable make a strong and difficult vault password manageble.

**Comment by perry-mitchell** [comment] 2023-05-04 18:03
Dupe of #1089 - this is a huge undertaking, which failed the last time someone was generous enough to devote their time to implementing it. Hello is a beast and hard to integrate properly. I don't recall what the exact issue was last time but it was un-mergeable.

**Closed by perry-mitchell** 2023-05-04 18:03 UTC
