### ISSUE TITLE
Getting "unable to verify the first certificate" with self-signed cert [appimage]

### ISSUE THREAD

**Issue by hellium6** [buttercup/buttercup-desktop#1132] opened 2022-04-10 08:19 UTC
I have a local WebDAV server with Apache for use with Buttercup. It works ok when I use it with Firefox addon, but it doesn't when I try from Desktop app (appimage). I was able to add the vault just fine. It shows the .bcup inside as well when adding. But when I enter the vault password it shows a red error message at the top right corner saying:

> Vault unlock failed: Error invoking remote method 'unlock-source': Layerr: Failed unlocking vault source: Failed unlocking source: unable to verify the first certificate

My AppImage is `v2.14.2`, about dialog shows:

```
Desktop @ v2.14.2
Core @ v6.7.0

Flags: installed
```

I'm on Arch Linux x86_64. I have added the cert chain with:

```bash
sudo trust anchor --store certificate-chain.crt
```

The chain contains site, intermediate and root cert. `trust list` shows the cert:

```
$ trust list | grep -i sparkling
	label: Sparkling Intermediate CA
	label: Sparkling Root CA
```

With `curl -v https://<local IP>` I can connect just fine with a "*  SSL certificate verify ok." message:

```
$ curl -v https://192.168.1.199/
* Trying 192.168.1.199:443...
* Connected to 192.168.1.199 (192.168.1.199) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* CAfile: /etc/ssl/certs/ca-certificates.crt
* CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
* subject: CN=192.168.1.199; ST=Noord Holland; C=NL; O=Example Inc; OU=IT Dept
* start date: Apr 10 07:08:24 2022 GMT
* expire date: Apr 10 07:08:24 2023 GMT
* subjectAltName: host "192.168.1.199" matched cert's IP address!
* issuer: CN=Sparkling Intermediate CA; ST=Zuid Holland; C=NL; O=Sparkling Network; OU=Sparkling CA
* SSL certificate verify ok.
> GET / HTTP/1.1
> Host: 192.168.1.199
> User-Agent: curl/7.82.0
> Accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Sun, 10 Apr 2022 07:25:56 GMT
< Server: Apache/2.4.53 (Debian)
< Vary: Accept-Encoding
< Transfer-Encoding: chunked
< Content-Type: text/html;charset=UTF-8
< 
<!DOCTYPE HTML PUBLIC "-W3CDTD HTML 3.2 Final//EN">
<html>
< --- REST OF THE HTML CONTENT --- >
```

I can login to webdav storage with cadaver:

```
$ cadaver https://192.168.1.199/webdav/
Authentication required for WebDAV on server `192.168.1.199':
Username: someuser
Password: 
dav:/webdav/> ls
Listing collection `/webdav/': succeeded.
        test.bcup                        18356  Apr  7 21:27
dav:/webdav/> 
```

With Librewolf (Firefox) I can access the ip without adding any exceptions and addon can open the vault with password just fine. I can also add passwords. But the appimage can't open the vault showing above message.

If more details are necessary, I followed [this article](https://raymii.org/s/tutorials/OpenSSL_command_line_Root_and_Intermediate_CA_including_OCSP_CRL%20and_revocation.html) to create a self signed cert and [this article](https://www.server-world.info/en/note?os=Debian_11&p=httpd&f=9) to setup webdav on Apache on `https://<IP>/webdav/`. Apache is running on Debian 11 (bullseye).

I have looked into:
#1054 : I have cert chain installed and not sure if permission is relevant since Firefox addon works just fine and I can save passwords
#395 : Don't want to go through Let's Encrypt just for a local server

My guess is that it has something to do with appimage. It probably doesn't have access to system trust store. Not sure about it though.

EDIT: Add appimage version

**Comment by perry-mitchell** [comment] 2022-06-18 09:47
Hi,
I'm sorry for the inconvenience. But Buttercup has not yet had support for self-signed certificates. It's also not on my radar for implementation as I don't have the time nor need of it, but I would **accept PRs** across our app suite for such functionality.

Will close as a dupe of #398

**Closed by perry-mitchell** 2022-06-18 09:47 UTC

**Comment by casasfernando** [comment] 2023-06-24 11:58
@hellium6 in case you are interested I found a workaround for this issue. You can read the details in this comment: https://github.com/buttercup/buttercup-desktop/issues/398#issuecomment-1605429320
