### ISSUE TITLE
Can't add any entries

### ISSUE THREAD

**Issue by Gribnif** [buttercup/buttercup-desktop#1038] opened 2021-05-19 20:46 UTC
I'm new to Buttercup. I have installed the Desktop app v. 2.5.0/core v5.13.0 under MacOS 10.14.6. I have created a new, empty vault file on my local machine. When I try to create a new password entry, I get these errors in the console upon save:

electron/js2c/renderer_init.js:13 (electron) The remote module is deprecated. Use https://github.com/electron/remote instead.

log @ electron/js2c/renderer_init.js:13
2index.js:530 Uncaught (in promise) Error: Failed saving vault: Cannot read property 'createEntry' of null
    at EventEmitter.<anonymous> (index.js:530)
    at Object.onceWrapper (events.js:422)
    at EventEmitter.emit (events.js:315)
    at Object.onMessage (electron/js2c/renderer_init.js:93)

**Comment by perry-mitchell** [comment] 2021-05-31 06:48
Duplicate of #1045

Although this issue came earlier, the other has more information on reproducing this issue, so I'll close in favour of that one.

**Closed by perry-mitchell** 2021-05-31 06:48 UTC
