### ISSUE TITLE
Search function doesn't work with Dropbox archive on 1.20.2 Buttercup version (macOS)

### ISSUE THREAD

**Issue by FalloutXtreme** [buttercup/buttercup-desktop#926] opened 2020-07-12 09:35 UTC
Hello,

I updated Buttercup to the last version (1.20.2) on macOS Catalina (10.15.5) and the search function (CMD+F) return me an error (see attachment).

I tried to remove and reinstall Buttercup but I have the same error.

To solve this issue, I guess we'll have to wait for an update.

EDIT : I tried with My Buttercup archive (alpha) and I have the same result.

<img width="952" alt="Capture d’écran 2020-07-12 à 11 14 39" src="https://user-images.githubusercontent.com/43672833/87243139-b5c23000-c433-11ea-9a98-8e467ebef7b6.png">

**Comment by sallar** [comment] 2020-07-12 12:54
Duplicate of #927, Closing this. Let's continue there.

**Closed by sallar** 2020-07-12 12:54 UTC
