### ISSUE TITLE
Windows desktop app gives error on startup on Windows 10 v1709

### ISSUE THREAD

**Issue by jdrch** [buttercup/buttercup-desktop#602] opened 2018-04-27 14:33 UTC
After installing the app and attempting to start it, I get the following error message:

![image](https://user-images.githubusercontent.com/1056759/39367942-d1d6305a-49fd-11e8-8759-5e9342e7c200.png)

Interestingly, Pulse SMS (which apparently uses the same build/application framework) has a similar [issue](https://github.com/klinker-apps/messenger-issues/issues/656).

Any ideas?

**Comment by perry-mitchell** [comment] 2018-04-27 20:10
Very interesting, thanks for reporting! Unfortunately this might go the same way as the other issue, and require someone to reproduce it in development.

@jdrch What version windows are you running? Perhaps you could share your PC details to get us started..

**Comment by jdrch** [comment] 2018-04-27 20:13
Windows 10 Pro x64 FCU (which I think is version 1709 as said in the OP title.)

**Comment by perry-mitchell** [comment] 2018-04-27 20:24
Ah sorry! Missed that..

**Comment by arunikayadav42** [comment] 2018-05-04 11:32
Hello all I am e beginner in open source and have a basic knowledge of javascript and want to get started with contributing to this project!Can somebody please help me?

**Comment by sallar** [comment] 2018-05-04 21:42
Hi @arunikayadav42! Welcome. What kind of help are you looking for?

**Comment by n8v8R** [comment] 2018-07-11 20:15
Well, isn't it the ol' unfixed https://github.com/buttercup/buttercup-desktop/issues/502 ?

**Comment by sallar** [comment] 2018-07-27 07:01
@n8v8R @jdrch if these two issues are the same should we close this in favor of the other one?

**Comment by n8v8R** [comment] 2018-07-27 09:38
it is for the developer to decide when/which issues are duplicate and reference/merge/close such accordingly. 

if the new version is meant to be version 1.9 than the issue is persistent and the developer would know this from testing and not musing here whether it been fixed.

it is not good that the [developer appears a bit ignorant](https://www.reddit.com/r/electronjs/comments/8y6orr/app_crashing_due_to_windows_aslr_setting/) about the (security) capabilities of Electron and potential implications of the app.

if you went over to https://github.com/electron/electron you would be wondering why there is no ALSR ticket considering the [long list](https://electronjs.org/apps) of other desktop apps (whith likely broader spread than BC)  or 

> Googling results in very little on the matter

and thus I would surprise me if it is a matter of Electron rather than implementation. 

Apprently though BC is not is not the only app suffering this https://github.com/Automattic/wp-desktop/issues/436

Why not open a ticket on Electron and get in touch with the Electron devel?

The way this is being handled, notwithstanding being present in the first place, does not inspire trust in BC - the app supposedly handling passwords.

**Comment by perry-mitchell** [comment] 2018-07-27 10:01
> it is not good that the developer appears a bit ignorant about the (security) capabilities of Electron and potential implications of the app.

@n8v8R Look, I'm not familiar with every possible platform feature on Windows Mac and Linux. I understand what we're building, and rely on the help of the community and other developers to see us through to the best possible implementation. I posted in Reddit seeking help as it was the right thing to do when I don't personally have experience with ASLR. 

These comments are not helpful, and I'd kindly request that you keep on topic and refrain from making these kinds of comments.

> and thus I would surprise me if it is a matter of Electron rather than implementation.

I don't currently see how it could be us, especially if other, non-related apps are experiencing the same issue. That being said, we'll take both possibilities into account.

> The way this is being handled, notwithstanding being present in the first place, does not inspire trust in BC - the app supposedly handling passwords.

You seem to miss the point, repeatedly. We're 2 people.. there are **other responsibilities** in this project, and in our lives, that require our attention ahead of this issue. We will handle it in due time. If you cannot help, or will not help, then please, refrain from commenting further on the topic.

**Comment by perry-mitchell** [comment] 2018-07-27 10:02
This does appear to be a dupe of #502, so I'll close this in favour.

**Closed by perry-mitchell** 2018-07-27 10:02 UTC
Labels: Platform: Windows, Priority: High, Status: Available, Type: Bug
