### ISSUE TITLE
release 18.1 KO ?

### ISSUE THREAD

**Issue by Crush33** [buttercup/buttercup-desktop#317] opened 2017-07-19 14:44 UTC
hi folks,

just updated my windows client of Buttercup from 18.0 (?) to 18.1 and got this when trying to launch :

![image](https://user-images.githubusercontent.com/2492697/28372962-5f5193c4-6ca1-11e7-88d8-f02aba1f1ae1.png)

Am I the only one getting this ?

Thx for any help :)

**Comment by perry-mitchell** [comment] 2017-07-19 15:06
Hi! Apologies for this.. seems we have some issues on our windows build. We'll try to get this resolved today (hopefully)..

**Comment by perry-mitchell** [comment] 2017-07-19 15:48
This is a duplicate of #311, so I'm closing.

**Closed by perry-mitchell** 2017-07-19 15:48 UTC
