### ISSUE TITLE
1.12.1 not working on macOS Mojave

### ISSUE THREAD

**Issue by andradei** [buttercup/buttercup-desktop#710] opened 2018-11-28 21:52 UTC
I was prompted for an update today, and after it was done, buttercup stopped working.

I downloaded it from the website and reinstalled, but it still won't open.

**Comment by segler** [comment] 2018-11-28 22:17
macOS Sierra is afected too. But previous version (1.12.0) is still working.

**Comment by perry-mitchell** [comment] 2018-11-29 05:08
![image](https://user-images.githubusercontent.com/3869469/49200460-96cd7200-f3a5-11e8-8507-6b974b8f6ac3.png)

Confirmed ☹️

**Comment by sallar** [comment] 2018-11-29 05:46
The issue is caused by electron-builder a damaged file randomly. I ran the build again with the exact same config as before and it fixed the issue. I'm building a new patch and uploading it now, hopefully we can have a look at it to see why did it break.

**Comment by sallar** [comment] 2018-11-29 19:41
This issue is fixed in the latest release

**Closed** 2018-11-29 19:41 UTC
Labels: Platform: Mac, Priority: Critical, Status: Available, Type: Bug
