### ISSUE TITLE
Search does not span folders 

### ISSUE THREAD

**Issue by wgregori** [buttercup/buttercup-desktop#314] opened 2017-07-14 14:17 UTC
When searching for a password entry the search does not span across folders.  You have to choose the folder then perform the search. Is this the desired result?

**Comment by perry-mitchell** [comment] 2017-07-14 14:24
This is currently underway when fuzzy search is upgraded. Sallar? 😊

**Comment by sallar** [comment] 2017-07-14 18:59
@perry-mitchell @wgregori yes this will be done in #136 :) This is duplicate of that so will close :) But thanks for reporting it @wgregori! Cheers

**Comment by perry-mitchell** [comment] 2017-11-24 10:52
This can be easily added to the desktop application using the `EntryFinder` class in [buttercup core](https://github.com/buttercup/buttercup-core/blob/master/API_WEB.md#EntryFinder).

**Comment by hugo-cardenas** [comment] 2017-11-29 14:47
What were you thinking about this, UX wise? 

- Should the new across-folders search completely replace per-folder search, just with the same UI?
  - In case yes, as the results would be potentially a mix of entries from all folders, should it visually "deselect" the folder previously selected?
  - Also, when selecting each of the entries in search results, should it mark its parent folder as selected, to show to which folder it belongs?
- Another fully different alternative (as 1Password does, for example) is having instead a dynamically generated "All items" folder, so that actually the search would just work the same as it does now, only that you would select that folder if you would want to search across all (not sure if this plays well with how entries are stored in buttercup-core)

**Comment by perry-mitchell** [comment] 2017-11-29 14:56
I actually quite like the "All Items" group.. That's a good idea. What do you think @sallar? It would most likely need to be made available in the core, so that every application could easily benefit from it.

I think when searching it should clear the currently selected group..

**Comment by ph1p** [comment] 2017-11-29 23:05
This is my actual search and I added the `EntryFinder` class. I've only one problem. How can I find the group of an entry? I think this is important, because I can't switch folders without this feature.

![kapture 2017-11-29 at 23 48 18](https://user-images.githubusercontent.com/15351728/33403228-cb313960-d55f-11e7-8856-586cdc682f57.gif)

Don't wonder about: 
- Hidden entry sidebar
- Search in tree view
- entry count next to folders
- titlebar icons
- color (I removed the vibrancy effect to get rid of the mac os bug)
These things are all tests of mine and not for production use or something else.

**Comment by darsain** [comment] 2018-02-21 10:09
Having to click some "All Items" folder before I can search globally would be very annoying. Not to mention it would clutter my directories with another directory I didn't create and can't get rid of. This can easily be solved with UX.

- Ctrl+F (optional, or just ↓)
- start typing
- buttercupt displays found items as it does now, but searched globally
- navigating with up/down arrows (or clicking) selects & activates the item in the list
- pressing escape clears the searchbox and displays the directory of the currently active item

Regarding active directory confusion while searching, just create a simple rule: always activate/select a directory of currently active item. For once it makes sense, and also when I'm navigating through search results, I can see which folder the items is in, because it lights up. And when I press escape, I'm in this folder.

This UX requires the least amount of steps and time to accomplish the needed action.

**Closed** 2018-02-24 18:20 UTC
Labels: Effort: Low, Priority: Medium, Status: Available, Type: Enhancement
