### ISSUE TITLE
Share-able archives using QR code

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-desktop#349] opened 2017-10-07 21:51 UTC
Add the ability to share archives by showing a QR code. The code modal/page could be presented by right-clicking on an **unlocked** archive.

Once requested, the QR code could be generated by using the following string:

`bcup-archive:1:credentialsHash`

Where **credentialsHash** is the output of securing a credentials instance using the master password. When scanned by the mobile app (or another application), the master password must be used to decrypt it and add it to the app.

**Comment by sallar** [comment] 2017-10-07 21:56
@perry-mitchell isn't this a duplicate of #306?

**Comment by perry-mitchell** [comment] 2017-10-08 05:47
Yes 😎

**Closed** 2017-10-08 05:47 UTC
Labels: Effort: High, Priority: Medium, Type: Enhancement
