### ISSUE TITLE
start minimized

### ISSUE THREAD

**Issue by v0ltmn** [buttercup/buttercup-desktop#1229] opened 2023-07-11 07:52 UTC
hi everyone! buttercup is the best, tnx)

is there a simple solution how to launch buttercup minimized on startup (macosx)? like a system menu icon only?

**Comment by georglauterbach** [comment] 2023-07-11 08:51
I'd love to see this as well :)

**Comment by Oxalin** [comment] 2023-11-24 18:39
I'm working on this feature while I'm also adding an option to run Buttercup at session launch. The switches have been added, but now I need to add the logic.

What I intend to do is launch the app in tray (or similar depending of the OS) if the option is enabled when running the app. If the app is called a second time (it's already running and we try to run it a second time), it will open the main window.

**Comment by Oxalin** [comment] 2023-11-25 02:35
Done. And it is now also possible to enable start at session launch. However, I'm not used to code in Typescript, so I'll send a PR and I realize I may have to make some tweaks to the code.

I tested the result under Windows and it works great.

Stay tuned

**Comment by georglauterbach** [comment] 2023-11-25 09:57
I can test on macOS if you give me instructions on how I'd do that :)

**Comment by Oxalin** [comment] 2023-11-25 15:41
@georglauterbach If I could, I would gladely create a package for you, but I can't build a package for macOS from Windows or Linux, one of the dependencies (dmg-license) is restricted to macOS.

So you would have to clone my git repo, install Node.js and install the dependencies. Then start the development code or create a package. How confident are you?

**Comment by georglauterbach** [comment] 2023-11-25 15:56
It's a matter of time I guess; though, time is something I lack at the moment.. TBH I think I won't be able to do this anytime soon, but in case an opportunity arisis, I will come back to this.

**Comment by Oxalin** [comment] 2023-11-25 16:16
No problem. If anyone else is whiling to build it on macOS, let me know.

That being said, this feature is now tested under Windows and Linux without any problem. So I'm pretty confident it will work on macOS, since it is mostly only a matter of reading the state of an option and showing or not the main window at launch.

**Comment by georglauterbach** [comment] 2023-11-25 16:39
I can test Linux easier. What do I need to do?

**Comment by Oxalin** [comment] 2023-11-25 17:36
I tested it this morning under ArchLinux already and it works fine (AppImage and native package). If you want to test it on a different distribution, I can provide the AppImage or you would need to create your own native package.

**Comment by georglauterbach** [comment] 2023-11-25 18:15
If you provide me with the AppImage, I can test on Ubuntu 22.04.

**Comment by Oxalin** [comment] 2023-12-01 01:14
This feature (start in background) has been merged in 2.23.0 with my NSIS series. Please, let me know if you encounter any problem (tested on Linux and Windows)

**Comment by v0ltmn** [comment] 2023-12-01 06:28
wow thnx guys you're the best! one thing.

now when i'm starting butter cup and trying to unlock a vault there is no text field in modal window; is this issue related to our new feature? i'm using mac

<img width="520" alt="Screenshot 2023-12-01 at 09 24 29" src="https://github.com/buttercup/buttercup-desktop/assets/107152491/8820f07e-7cc8-411f-ba2f-9cc1b34aeb03">

**Comment by perry-mitchell** [comment] 2023-12-01 06:28
Thanks for the good work @Oxalin!

**Comment by v0ltmn** [comment] 2023-12-01 06:30
@perry-mitchell nop

**Closed** 2023-12-01 06:32 UTC
Labels: Priority: Medium, Type: Enhancement, Status: Completed, Platform: Mac, Platform: Windows, Platform: Linux

**Comment by georglauterbach** [comment] 2023-12-05 11:26
> wow thnx guys you're the best! one thing.
> 
> now when i'm starting butter cup and trying to unlock a vault there is no text field in modal window; is this issue related to our new feature? i'm using mac
> <img alt="Screenshot 2023-12-01 at 09 24 29" width="520" src="https://private-user-images.githubusercontent.com/107152491/287174244-8820f07e-7cc8-411f-ba2f-9cc1b34aeb03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NzU4MjksIm5iZiI6MTcwMTc3NTUyOSwicGF0aCI6Ii8xMDcxNTI0OTEvMjg3MTc0MjQ0LTg4MjBmMDdlLTdjYzgtNDExZi1iYTJmLTljYzFiMzRhZWIwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNVQxMTI1MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OGNhOGRjNjhlY2JmYTk4MmI5YTk2NmE0MjI5YWJjYzgxNzM5ZGY0NjRhMjg1YzEyNGQ5YjE0MzBkNDUwODkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YOfcTJnKXtX8nni8Qqh7p_8wjyzKm-qlmCDAvGmhqxo">

I am seeing the same issue. @v0ltmn did you solve the problem, or is there a follow-up issue? I have both "Auto-start application when my session launches" and "Start application in background" enabled to create the issue.

**Comment by Oxalin** [comment] 2023-12-06 01:58
> wow thnx guys you're the best! one thing.
> 
> now when i'm starting butter cup and trying to unlock a vault there is no text field in modal window; is this issue related to our new feature? i'm using mac
> <img alt="Screenshot 2023-12-01 at 09 24 29" width="520" src="https://private-user-images.githubusercontent.com/107152491/287174244-8820f07e-7cc8-411f-ba2f-9cc1b34aeb03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4Mjc5MDgsIm5iZiI6MTcwMTgyNzYwOCwicGF0aCI6Ii8xMDcxNTI0OTEvMjg3MTc0MjQ0LTg4MjBmMDdlLTdjYzgtNDExZi1iYTJmLTljYzFiMzRhZWIwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNlQwMTUzMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMTlhNTFiMThjMmM0OGFkODYxZWFlNzVjNjcyOTU2NDM3N2RhN2M1MTM3Y2UwYmY0MDM5MDAzYjM1ZGE5MmQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xFQqLrX3mvFoyjj31o1Gob0mpcMEaDl8B0sN4vXJm4w">

It should have any link. The feature only add a check when it is ready to display the mainWindow just after launch. If this was to be the cause, then we would need to also check with the "--hidden" argument that was already present.

**Comment by perry-mitchell** [comment] 2023-12-09 21:17
This introduced a new bug: #1260
