### ISSUE TITLE
As a desktop user when I attempt to use keyboard shortcuts / hotkeys they don't work #Bug #Help

### ISSUE THREAD

**Issue by ldexterldesign** [buttercup/buttercup-desktop#1034] opened 2021-05-17 08:20 UTC
Hi!

I hope you're 👌

Thanks for wonderful software

As title

[ ] cmd + m (minimise)
[ ] cmd  + h (hide)
[ ] cmd + w (close)
[x] cmd + q (quit)

If you're reading and:
- agree, then please vote up (e.g. +1, like), or;
- disagree, then please vote down (e.g. -1, dislike) - I'd love to know why?

If you have any issues (e.g. questions/queries) then happy to help

Hope this helps and keep up great work!

Sincerely

hardware: Apple, MacBook Pro (16-inch, 2019)
software - OS: Apple, macOS, 11.3.1 (20E241)
software - application: BC, Desktop @ v2.4.0 Core @ v5.13.0 Flags: installed

**Comment by perry-mitchell** [comment] 2021-05-17 18:56
Dupe of #1009 - But great points here.

Please follow that issue for progress.

**Closed by perry-mitchell** 2021-05-17 18:56 UTC
