### ISSUE TITLE
iOS - app bug when opening Vault

### ISSUE THREAD

**Issue by Valiumm** [buttercup/buttercup-desktop#1246] opened 2023-11-06 09:21 UTC
Hy There !

Just to let you know I have a bug when I'm trying to use this app on iOS device. 
It append on several version of iOS 

Basically, when I want to unlock the safe, it show me for 1s the content and redirect automatically to the logo of the App.
I use to click quite fast of the first list I can reach to avoid this issue but that's is no longer working.

That is working on other device so still usable 

Thanks for your works !

**Comment by perry-mitchell** [comment] 2023-11-22 20:05
Hi, this is a dupe of https://github.com/buttercup/buttercup-mobile/issues/308. Thanks for reporting!

**Closed by perry-mitchell** 2023-11-22 20:05 UTC
