### ISSUE TITLE
Two 'Te' archive in the left bar that I haven't created...how do I delete please?

### ISSUE THREAD

**Issue by mannp** [buttercup/buttercup-desktop#459] opened 2017-12-15 17:37 UTC
Arch linux version from pacaur.0.25.1-1

Thanks

**Comment by sallar** [comment] 2017-12-17 10:39
@mannp Did this happen the first time you installed the app? You have never used Buttercup before? 
Also can you please try unlocking the archives using the password: `1` to see if it unlocks?

**Comment by mannp** [comment] 2017-12-17 22:07
@sallar not the first time no, it only happened on the last update on AUR.

If I enter a password of '1' it gives me an error of 'archive source not found'.

I thought these were maybe left after the test process as part of the install, but as they only happened on the last update I wasn't sure.

**Comment by sallar** [comment] 2017-12-18 10:04
@mannp Could you do us a favor?
Delete your copy and:

1- Install from AUR again, to see if the issue is still there
2- Delete the AUR again and this time download a copy from our Github releases page to see if it's any different.

Thanks.

**Comment by mannp** [comment] 2017-12-19 11:08
Will do, will let you know shortly.

**Comment by mannp** [comment] 2017-12-19 21:48
So I have removed buttervup desktop and removed its config. Rebuilt it using AUR latest version 0.25.2-1 and on start I immediately have a 'Te' archive in the left bar.

If I enter a password of '1' it says the archive is not found and one time it gave me the following error.

> Unhandled Error
> Error: Object has been destroyed
>     at BrowserWindow.win.on.__WEBPACK_IMPORTED_MODULE_1_lodash_debounce___default (/usr/lib/buttercup-desktop/resources/app.asar/dist/app.js:96015:93)
>     at invokeFunc (/usr/lib/buttercup-desktop/resources/app.asar/dist/app.js:36766:19)
>     at trailingEdge (/usr/lib/buttercup-desktop/resources/app.asar/dist/app.js:36813:14)
>     at Timeout.timerExpired [as _onTimeout] (/usr/lib/buttercup-desktop/resources/app.asar/dist/app.js:36801:14)

I will now try by downloading the code directly.

**Comment by sallar** [comment] 2017-12-21 20:49
@mannp That `npm test` is what's creating those archives. Ping @sum01.
If the npm test can not be removed from the arch PKGBUILD then I'll have to add a cleanup phase to the tests. But the thing is tests are creating the archives in user's data directory which in theory "should not" end up in the resulting archive...

**Comment by sum01** [comment] 2017-12-21 21:49
Sure, I can remove the `check()` from the PKGBUILD. It's purely optional, and I was only doing it for completeness.

**Comment by sallar** [comment] 2017-12-22 09:50
@mannp can you verify that it works?
@sum01 I need to fix the master. we reverted and package versions are now different.

**Comment by sum01** [comment] 2017-12-22 19:40
@sallar Unless the fixed master is tagged, I can only either revert to `0.25.1`, or build from the commit that increments to `0.25.2`. Unsure of which you'd want, but I think tags are the better option, no?

**Comment by mannp** [comment] 2017-12-29 21:26
@sallar I cannot verify as I canot get buttercup to build due to an electron build issue.

**Comment by sum01** [comment] 2017-12-29 22:18
Can probably close this since I removed the `check()` from the PKGBUILD, so it shouldn't create these anymore. @mannp

**Comment by mannp** [comment] 2017-12-31 10:43
@sum01 thanks for the changes and @sallar thanks for the help; closing as this is now resolved for me.

**Closed** 2017-12-31 10:43 UTC
Labels: Platform: Linux, Status: Pending, Type: Bug
