### ISSUE TITLE
Buttercup does not automatically lock up vault after some time

### ISSUE THREAD

**Issue by tigrouind** [buttercup/buttercup-desktop#1075] opened 2021-08-09 08:36 UTC
I have setup the following options in "Preferences" dialog :  
![image](https://user-images.githubusercontent.com/2211721/128676528-3fbaa67c-2ded-4f15-a206-00b1d4a3be98.png)

Here is what I got after reducing butter cup (by clicking on minimize icon), waiting 5 minutes or more, and opening it again : the vault is still open.
![image](https://user-images.githubusercontent.com/2211721/128678661-48db1cce-5dc5-401a-8709-8becbd3fe6ca.png)

The only case the vault is locked automatically is if I click on the close icon (so it only appear in quick launch).

Or does "2m" actually mean "2 minutes of inactivity on the computer". Not just "leaving buttercup 2 minutes alone" ?

**Comment by julianpoemp** [comment] 2021-08-10 19:11
Duplicate of #1033

**Comment by tigrouind** [comment] 2021-08-10 22:17
> Duplicate of #1033

I know it's a free and open source project but it's crazy that 3 months later it hasn't been fixed yet (especially there is security concerns)

**Comment by perry-mitchell** [comment] 2021-10-03 14:11
@tigrouind You're welcome to submit a PR.

**Closed by perry-mitchell** 2021-10-03 14:11 UTC
