### ISSUE TITLE
503 error while saving

### ISSUE THREAD

**Issue by aesthicc** [buttercup/buttercup-desktop#817] opened 2019-10-13 14:47 UTC
I'm getting the same issue as [#780 ](https://github.com/buttercup/buttercup-desktop/issues/780) in 1.17.0

1.16.2 is still working just fine.

`Unhandled Promise Rejection
Error: Request failed with status code 503
    at e.exports (file:///Applications/Buttercup.app/Contents/Resources/app.asar/dist/main.bundle.js:361:269668)
    at e.exports (file:///Applications/Buttercup.app/Contents/Resources/app.asar/dist/main.bundle.js:384:2582)
    at XMLHttpRequest.d.onreadystatechange (file:///Applications/Buttercup.app/Contents/Resources/app.asar/dist/main.bundle.js:361:268605)`

**Comment by perry-mitchell** [comment] 2019-10-16 17:58
@aesthicc Please include more details. OS, type of connection, when did the issue occur (opening/saving).

**Comment by aesthicc** [comment] 2019-10-16 18:01
Same as [#780 ](https://github.com/buttercup/buttercup-desktop/issues/780)
Mac, nextcloud, happens when saving an entry

**Comment by perry-mitchell** [comment] 2019-10-16 18:27
Ok, thanks for clarifying.

A 503 is a **Service Unavailable** error - so really anything could be wrong here. Are you at all able to look at the network to see what's being requested? You can toggle the devtools before trying to save:

![image](https://user-images.githubusercontent.com/3869469/66947437-9096c180-f05b-11e9-9fd1-6c0dbc64c700.png)

The network tab would show a red result once you try to save. Don't post all of the results here (obviously your domain, what you're sending etc. should all be kept secret).. but you can confirm that the URL is correct. Nextcloud should probably be something like `https://server.com/remote.php/webdav/path/to/my/file.bcup`.

**Comment by aesthicc** [comment] 2019-10-16 20:14
The URL is correct, same as in 1.16.2. Other than that, there are many differences in the headers but I'm not sure what to look for.

**Comment by fmommeja** [comment] 2019-10-22 08:23
Hi,
I'm having the exact same error while saving on a nextcloud based WebDav.

Configuration : Buttercup Version 1.17.1 (1.17.1)
MacOS Sierra v. 10.12.6 (16G2136)

**Comment by sallar** [comment] 2019-10-22 08:43
Seems like this is a duplicate of #825
I've created a PR that fixes both issues. Should be released soon.

**Closed** 2019-10-22 10:42 UTC

**Comment by fmommeja** [comment] 2019-10-22 11:49
Still happening with 1.17.2 

`Unhandled Promise Rejection
Error: Request failed with status code 503
    at e.exports (file:///Applications/Buttercup.app/Contents/Resources/app.asar/dist/main.bundle.js:361:269668)
    at e.exports (file:///Applications/Buttercup.app/Contents/Resources/app.asar/dist/main.bundle.js:384:2582)
    at XMLHttpRequest.d.onreadystatechange (file:///Applications/Buttercup.app/Contents/Resources/app.asar/dist/main.bundle.js:361:268605)`

Configuration : Buttercup Version 1.17.2 (1.17.2)
MacOS Sierra v. 10.12.6 (16G2136)

**Comment by aesthicc** [comment] 2019-10-22 15:21
Same for me, still getting 503 in 1.17.2

**Comment by perry-mitchell** [comment] 2019-10-24 19:02
503 is most likely something to do with the server you're connecting to. Please double check your URLs. New archives can no longer be created directly for ownCloud or Nextcloud, only webdav is available for new connections.

Please ensure you have the `/remote.php/webdav` suffix for new OC/NC connections.

**Comment by fmommeja** [comment] 2019-10-24 19:25
@perry-mitchell That is the case.
I was using `https://ncloud.zaclys.com/remote.php/webdav` when I reported this error.

**Comment by aesthicc** [comment] 2019-10-25 18:54
@perry-mitchell The urls don't seem te be the problem. Checked and double checked.

I just tried to connect to my cloud source again in 1.17.2
	- was able to connect to the server with my webdav url - https://my.nextcloud.provider.org/remote.php/webdav/
	- selected my archive
	- got 503 when I entered the correct password to my archive

I will recap: 
	- This issue started in  1.16.0, was resolved in a later 1.16 release.
	- Was re-introduced in 1.17.0

**Comment by perry-mitchell** [comment] 2019-10-31 18:57
It would be great if someone could look at the request, and try to reproduce in Postman or something to see if it's just the request or something else. We can't reproduce this with OC right now, so we'd appreciate the help.

**Comment by aesthicc** [comment] 2019-11-03 17:57
Could you tell me all the values I should enter in https://postwoman.io ?

**Comment by perry-mitchell** [comment] 2019-11-06 15:12
You’d need to pretty much copy the request that you see in the devtools for the app. The URL, method, and then the headers and potentially body (if it’s a POST request).

**Comment by aesthicc** [comment] 2019-11-06 16:26
![1](https://user-images.githubusercontent.com/32882701/68316853-0d90e600-00b2-11ea-9fc6-97ea1df3abf6.png)
