### ISSUE TITLE
LinuxLite - Google Drive Authentication fails to create Vault

### ISSUE THREAD

**Issue by KF6IF** [buttercup/buttercup-desktop#1179] opened 2022-12-02 15:33 UTC
When you try to create a Google Drive Vault, Chrome opens to associate your Google account with Buttercup and when you finish that, an error message pops up stating; "Faild to open URL " buttercup://auth/google/callback?-googledesktopauth&code=4/0 .... " . At the bottom is states "The specified location is not supported." 

Any help would be appreciated. 

tnx,
phil

**Comment by perry-mitchell** [comment] 2023-02-02 12:09
Sorry that it's been a while.

This is a protocol registration error in your OS - it needs to support protocol registrations for this to work correctly. The desktop application registers `buttercup://` in your OS so that these URLs can be executed elsewhere (like in the browser) and have the link be executed finally by Buttercup desktop.

When buttercup starts it registers this protocol. So this step is obviously not working on LinuxLite or perhaps just your install.. I'm not sure.

As this is working on Ubuntu (as well as Mac OS and Windows), I suspect that the problem is in fact LinuxLite or elsehwere, so I'll have to close this issue for now.

If you find a way to address it specifically for Linuxlite, or find another issue where this occurs for other Electron Apps running on that OS, I'd consider reopening this. We physically can't debug all OS-specific issues like this due to time, hope you understand.

**Closed by perry-mitchell** 2023-02-02 12:09 UTC

**Comment by KF6IF** [comment] 2023-02-02 15:44
I uninstalled the program.
