### ISSUE TITLE
Issue with v2.27.0 update

### ISSUE THREAD

**Issue by spixdot** [buttercup/buttercup-desktop#1328] opened 2024-04-13 19:00 UTC
Update failed: New version 2.27.0 is not signed by the application owner: publisherNames: Vault Garden, raw info: { "SignerCertificate": { "FriendlyName": "", "IssuerName": { "Name": "CN=Sectigo Public Code Signing CA R36, O=Sectigo Limited, C=GB", "Oid": "System.Security.Cryptography.Oid" }, "NotAfter": "/Date(1717718399000)/", "NotBefore": "/Date(1654560000000)/", "PrivateKey": null, "PublicKey": { "Key": "System.Security.Cryptography.RSACryptoServiceProvider", "Oid": "System.Security.Cryptography.Oid", "EncodedKeyValue": "System.Security.Cryptography.AsnEncodedData", "EncodedParameters": "System.Security.Cryptography.AsnEncodedData" }, "SerialNumber": "51308BBDCB43A3B863439D11A735C4FB", "SignatureAlgorithm": { "Value": "1.2.840.113549.1.1.12", "FriendlyName": "sha384RSA" }, "Thumbprint": "DBBB825FB465D7153D58BEAC559195A16B4BF07C", "Version": 3, "Issuer": "CN=Sectigo Public Code Signing CA R36, O=Sectigo Limited, C=GB", "Subject": "CN=MadDev Oy, O=MadDev Oy, S=Uusimaa, C=FI" }, "TimeStamperCertificate": { "Archived": false, "Extensions": [ "System.Security.Cryptography.X509Certificates.X509KeyUsageExtension", "System.Security.Cryptography.X509Certificates.X509BasicConstraintsExtension", "System.Security.Cryptography.X509Certificates.X509EnhancedKeyUsageExtension", "System.Security.Cryptography.X509Certificates.X509Extension", "System.Security.Cryptography.X509Certificates.X509Extension", "System.Security.Cryptography.X509Certificates.X509SubjectKeyIdentifierExtension", "System.Security.Cryptography.X509Certificates.X509Extension", "System.Security.Cryptography.X509Certificates.X509Extension" ], "FriendlyName": "", "IssuerName": { "Name": "CN=DigiCert Trusted G4 RSA4096 SHA256 TimeStamping CA, O=\"DigiCert, Inc.\", C=US", "Oid": "System.Security.Cryptography.Oid" }, "NotAfter": "/Date(2044396799000)/", "NotBefore": "/Date(1689292800000)/", "HasPrivateKey": false, "PrivateKey": null, "PublicKey": { "Key": "System.Security.Cryptography.RSACryptoServiceProvider", "Oid": "System.Security.Cryptography.Oid", "EncodedKeyValue": "System.Security.Cryptography.AsnEncodedData", "EncodedParameters": "System.Security.Cryptography.AsnEncodedData" }, "SerialNumber": "0544AFF3949D0839A6BFDB3F5FE56116", "SubjectName": { "Name": "CN=DigiCert Timestamp 2023, O=\"DigiCert, Inc.\", C=US", "Oid": "System.Security.Cryptography.Oid" }, "SignatureAlgorithm": { "Value": "1.2.840.113549.1.1.11", "FriendlyName": "sha256RSA" }, "Thumbprint": "66F02B32C2C2C90F825DCEAA8AC9C64F199CCF40", "Version": 3, "Handle": 2548395202544, "Issuer": "CN=DigiCert Trusted G4 RSA4096 SHA256 TimeStamping CA, O=\"DigiCert, Inc.\", C=US", "Subject": "CN=DigiCert Timestamp 2023, O=\"DigiCert, Inc.\", C=US" }, "Status": 0, "StatusMessage": "Signature vérifiée." }

![image](https://github.com/buttercup/buttercup-desktop/assets/34375204/4e2d5b13-c9d3-4c5a-b3f8-206877b6db21)

**Comment by perry-mitchell** [comment] 2024-06-15 10:29
I'm still not able to reproduce this, and no one else has commented, so I'll close this for now.

I'd recommend uninstalling Buttercup and downloading a fresh copy of the latest version, if encountering this error.

**Closed by perry-mitchell** 2024-06-15 10:29 UTC
