### ISSUE TITLE
Dropbox updates: Unhandled Promise Rejection

### ISSUE THREAD

**Issue by aesthicc** [buttercup/buttercup-desktop#780] opened 2019-07-12 19:23 UTC
Unhandled Promise Rejection
Error: Request failed with status code 503
    at e.exports (file:///Applications/Buttercup.app/Contents/Resources/app.asar/dist/main.bundle.js:356:254552)
    at e.exports (file:///Applications/Buttercup.app/Contents/Resources/app.asar/dist/main.bundle.js:369:1318)
    at XMLHttpRequest.h.(anonymous function) (file:///Applications/Buttercup.app/Contents/Resources/app.asar/dist/main.bundle.js:356:253550)

I get this error when saving an entry.

OS: macOS 10.14.5
Version: v1.16.0

**Comment by sallar** [comment] 2019-07-12 19:33
Hi @aesthicc what cloud provider are you using? This looks like an error with your provider.

**Comment by aesthicc** [comment] 2019-07-12 19:40
Ah i see, it's a nextcloud instance. It could also be my firewall, I will look into it.
Thanks.

**Comment by aesthicc** [comment] 2019-07-13 18:26
For some reason the 1.15.0 release does allow me to save an entry. I found no issues with my firewall. I have not yet reported an issue to my nextcloud provider, should I?

**Comment by rwolf449** [comment] 2019-07-16 09:09
We have the same issue when we try to save something in owncloud, but with status code 500:

Unhandled Promise Rejection
Error: Request failed with status code 500
    at t.exports (webpack-internal:///./node_modules/buttercup/dist/buttercup-web.min.js:8:254827)
    at t.exports (webpack-internal:///./node_modules/buttercup/dist/buttercup-web.min.js:22:1315)
    at XMLHttpRequest.p.(anonymous function) (webpack-internal:///./node_modules/buttercup/dist/buttercup-web.min.js:8:253825)

Adding a new connection to a server also doesnt work after the update, the console says:

Uncaught TypeError: createWebDAVClient is not a function
    at createWebDAVfs (index.js?1d68:48)
    at getFsInstance (auth.js?7dc9:64)
    at Webdav.e (webdav.js?d815:81)
    at HTMLUnknownElement.callCallback (react-dom.development.js?61bb:149)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?61bb:199)
    at invokeGuardedCallback (react-dom.development.js?61bb:256)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js?61bb:270)
    at executeDispatch (react-dom.development.js?61bb:561)
    at executeDispatchesInOrder (react-dom.development.js?61bb:583)
    at executeDispatchesAndRelease (react-dom.development.js?61bb:680)

OS: Windows 10 Pro Version 1803
Buttercup version: 1.16.0

**Comment by perry-mitchell** [comment] 2019-07-16 18:39
> react-dom.development.js

Hmm this looks interesting - You're not running a development copy are you @rwolf449? @sallar could this occur in prod?

> createWebDAVClient is not a function

This definitely seems like a webdav issue, but I can't reproduce this with my webdav connections in Buttercup. I've also checked all of the lock files, and all should be pointing to pre-2.0 `webdav` where `createWebDAVClient` should work fine.

**Comment by perry-mitchell** [comment] 2019-07-16 18:43
Yes seems this is more widely reproducible.. Apologies everyone! Please install 1.15 where possible. We'll have a patch out shortly.

**Comment by perry-mitchell** [comment] 2019-07-16 18:54
Seems like something broke with the Dropbox client we're using:

![image](https://user-images.githubusercontent.com/3869469/61321451-385de280-a814-11e9-872b-83f11a9c28d4.png)

**Comment by perry-mitchell** [comment] 2019-07-16 20:18
We currently have 2 options:
 * Revert the core and patch release (most likely)
 * Release updated core with new request library in dropbox client (upcoming)

**Comment by sallar** [comment] 2019-07-16 20:48
Reverting core and re-releasing...

**Comment by aesthicc** [comment] 2019-07-17 12:28
Version 1.16.1 is :ok_hand: for me.
Thanks

**Comment by perry-mitchell** [comment] 2019-07-19 18:44
Will close this for now. We can reopen if it's discovered to not be solved.

**Closed by perry-mitchell** 2019-07-19 18:44 UTC
Labels: Priority: Critical, Status: Available, Type: Bug
