### ISSUE TITLE
Can't connect Google Drive

### ISSUE THREAD

**Issue by psdl** [buttercup/buttercup-desktop#850] opened 2019-11-17 18:59 UTC
If i try to connect to Google Drive i get this error in version 1.17.2

In the Log there is no hint.

![buttercup](https://user-images.githubusercontent.com/21990483/69012293-790d6a00-0974-11ea-92f3-86272a88bf6f.JPG)

**Comment by Peppeo** [comment] 2019-11-18 10:14
Hi there, please doublecheck with Buttercup 1.17.3? I had the same issue (see: Closed #835) and it was resolved with 1.17.3. Best regards Mark

**Comment by Oxalin** [comment] 2019-11-18 21:18
Downloading the latest Buttercup app for desktop from buttercup.pw say it is 1.17.3. However, after installing it, version 1.17.2 is shown under Help menu.

**Comment by perry-mitchell** [comment] 2019-11-24 19:11
@Oxalin can you verify that no other instances are running before you start the newer version?

**Comment by moka491** [comment] 2019-11-26 19:35
<img width="950" alt="Bildschirmfoto 2019-11-26 um 20 32 03" src="https://user-images.githubusercontent.com/31903525/69666120-03984c80-108c-11ea-81b3-82818641f268.png">

I get the above mentioned error code, plus this message from Google when trying to sign in.
v1.18.0 on MacOS 10.15.1, fresh install via homebrew.

**Comment by sallar** [comment] 2019-11-27 12:24
@moka491 are you connected to a proxy or VPN service? And at what step of the process this message shows up? Can you see the login form before this?

**Comment by moka491** [comment] 2019-11-29 06:04
@sallar It happens right after the login, which itself seemed to be successful.
It also happens on the Windows build btw, and I tested different networks, including my home net (that has direct internet access)

**Comment by Oxalin** [comment] 2019-12-02 21:33
@perry-mitchell It is now irrelevant since 1.18.0 was released. Still, if I must reply, the version had been updated when installing the new version, not to the one expected. And no other instance was running at the time.

**Comment by perry-mitchell** [comment] 2019-12-11 17:33
![image](https://user-images.githubusercontent.com/3869469/70645147-18104380-1c4d-11ea-9258-c39d7dd34965.png)
 Confirmed.. definitely borked in the latest versions..

**Comment by sallar** [comment] 2019-12-12 12:31
Seems like that google has stopped supporting signing in from inside an embedded browser (eg Electron).

![image](https://user-images.githubusercontent.com/768052/70712263-0e89e880-1cec-11ea-8471-07251b6dc628.png)

I will try to fix this ASAP.

**Comment by prostomarkeloff** [comment] 2019-12-24 12:54
Any updates?

**Comment by alinleonard** [comment] 2019-12-27 08:49
up!

**Comment by sallar** [comment] 2019-12-27 11:52
Im working on this and soon will release an update. Sorry for the delay.

**Comment by sergio-hcsoft** [comment] 2019-12-27 11:58
Seems the only fix is usign a chromium-based browser to authenticate:
https://developers.google.com/identity/sign-in/web/troubleshooting

**Comment by sallar** [comment] 2019-12-27 12:00
@sergio-hcsoft Im moving the sign-in procedure from an in-app browser to user's default browser. Google doesn't allow embedded browsers to authenticate, even if it's chromium (electron is chromium based)

**Closed** 2019-12-30 10:29 UTC
Labels: Effort: Medium, Priority: Critical, Status: Available, Type: Bug
