### ISSUE TITLE
Custom Field Deletion Issue in Buttercup

### ISSUE THREAD

**Issue by trycoast** [buttercup/buttercup-desktop#1359] opened 2024-07-25 12:42 UTC
### Custom Field Deletion Issue in Buttercup

**Description:**
Whenever I delete a custom field and save, the field tends to re-appear.

**Steps to Reproduce:**
1. Delete a custom field.
2. Save the entry.
3. The deleted custom field re-appears.

**OS:**
- Windows 11

**Expected Behavior:**
The deleted custom field should not re-appear after saving.

**Actual Behavior:**
Deleted custom fields re-appear after saving.

**Additional Note:**
Certain changes to non-custom fields seem to cause custom fields to be ignored.

**Comment by perry-mitchell** [comment] 2024-08-05 18:36
Duplicate of #1342

**Closed by perry-mitchell** 2024-08-05 18:36 UTC
