### ISSUE TITLE
Can't open vaults. Failed mapping credentals. No valid signature in vault. 

### ISSUE THREAD

**Issue by zmnv** [buttercup/buttercup-desktop#934] opened 2020-07-24 00:52 UTC
All works fine until I get some buggy 'THERE IS NEW UPDATE' (as usual) window which I just skipped.
## But now I can't open any of my storages.

desktop:
**1.18.0**
![image](https://user-images.githubusercontent.com/25253501/88351873-7b745f00-cd60-11ea-9362-6dac3fba31dc.png)

**1.20.4**
![image](https://user-images.githubusercontent.com/25253501/88351960-cee6ad00-cd60-11ea-9951-6909f8996dfb.png)

I'm just in a shock.... All my works stops from now moment. Thanks..................................

----
macOS Catalina 10.15.6  (a few days ago it was Mojave)
vaults in flash drive

last vault files updates was a long time ago. no new changes in .bcup files.

the same error in browser

**Comment by zmnv** [comment] 2020-07-31 06:44
Im still stressed about it. Any info?

**Comment by zmnv** [comment] 2020-07-31 07:23
![image](https://user-images.githubusercontent.com/25253501/89010730-d2a5a100-d317-11ea-84ec-7fed3c9ab62a.png)

In which case it can happens? Looks like new versions of desktop application just broke my vaults.................

**Comment by zmnv** [comment] 2020-12-20 13:42
Any ideas how to restore encoding from unknown to text?

**Comment by perry-mitchell** [comment] 2021-02-20 21:38
Hi @zmnv - I'm sorry noone got to your issue in time. It looks like your file was corrupted, but it's unlikely that buttercup did this. Buttercup only writes **text** data, whereas that corruption is binary data. It's unlikely to be possible to restore. Backups are absolutely necessary for everyone storing critical items in vaults - you should always back up precious data.

As there's no known defect causing this, and the issue has been open a very long time, I'm going to close it. If you find a reproducible bug that causes this I'd happily re-open it.

Again, sorry for the inconvenience.

**Closed by perry-mitchell** 2021-02-20 21:38 UTC
