### ISSUE TITLE
Error upon reopening after some days (and releases)

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-desktop#269] opened 2017-05-29 11:00 UTC
I've left Buttercup open for about a week (taskbar), and after opening it again I get the following error:

![image](https://cloud.githubusercontent.com/assets/3869469/26547326/2261db24-4477-11e7-8ef8-2d8b6c55688a.png)

Obviously since last time there had been new releases, so I wonder if that could possibly cause this issue too.

**Comment by perry-mitchell** [comment] 2017-05-29 11:01
Closing the dialog and clicking the button half works:

![image](https://cloud.githubusercontent.com/assets/3869469/26547360/4e49b04a-4477-11e7-886b-92f85ab8da25.png)

**Comment by sallar** [comment] 2017-05-29 11:02
I saw this bug once, but couldnt reproduce it :(

**Comment by sallar** [comment] 2017-05-29 19:00
@perry-mitchell The cause is this call:

``` js
// Create a new window if all windows are closed.
__WEBPACK_IMPORTED_MODULE_1_electron__["app"].on('activate', () => {
  if (windowManager.getCountOfType('main') === 0) {
    windowManager.buildWindowOfType('main');
  }
});
```

Which calls:

``` js
buildWindowOfType(type, fn = null, options = {}) {
  const window = this._buildProcedures[type](fn, options);
  this.register(type, window);
  return window;
}
```

so something is losing state here

**Comment by sallar** [comment] 2017-12-21 20:46
This is actually done a long time ago. Dont know why it's still open. Closing :)

**Closed by sallar** 2017-12-21 20:46 UTC
Labels: Platform: Mac, Priority: High, Status: Available, Type: Bug
