### ISSUE TITLE
Hide-able custom fields

### ISSUE THREAD

**Issue by reddo** [buttercup/buttercup-desktop#462] opened 2017-12-17 16:09 UTC
Consider adding an option to set custom field to hide-able, as the password is (for other sensitive information).

**Comment by perry-mitchell** [comment] 2017-12-17 17:41
This will require significant changes to the platform, but is doable. It'll need an attribute added to the core. It'll probably need the [config library](https://github.com/buttercup/buttercup-config) to be finished and integrated first.

**Comment by codesmaker** [comment] 2018-02-22 11:45
Hi,

Any progress on this feature? It's really important because very often you have other sensitive data, beside the password, associate with an account.

Thanks for the hard work!

**Comment by perry-mitchell** [comment] 2018-02-22 11:54
Not yet sorry @codesmaker - There are many more higher-prio tasks before this one I'm afraid. It'll require that config library to be finished, which I'll hopefully get time for soon.

**Comment by codesmaker** [comment] 2018-02-22 14:07
@perry-mitchell Thanks for the reply! Keep up the good work guys!

**Comment by pft** [comment] 2018-10-23 13:54
Is this not a duplicate of #85?

**Comment by perry-mitchell** [comment] 2018-10-23 15:52
@pft Yes I think you’re right - thanks!

**Closed** 2018-10-23 15:52 UTC
Labels: Effort: High, Priority: Medium, Status: Available, Type: Enhancement
